const TeamData = [{'id': 1,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': '1.FSV Mainz 05'},
 {'id': 2,
  'primaryhex': '#FAFAFA',
  'secondaryhex': '#080878',
  'team': 'Bidvest Wits FC'},
 {'id': 3,
  'primaryhex': '#3456a1',
  'secondaryhex': '#78b3e3',
  'team': 'NK Osijek'},
 {'id': 4,
  'primaryhex': '#008056',
  'secondaryhex': '#FFFFFF',
  'team': 'Sporting CP'},
 {'id': 5,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Hokkaido Consadole Sapporo'},
 {'id': 6,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Ba FC'},
 {'id': 7,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Club Atlético San Martín (Tucumán)'},
 {'id': 8,
  'primaryhex': '#0b9c3b',
  'secondaryhex': '#f1f50c',
  'team': 'Tampa Bay Rowdies'},
 {'id': 9,
  'primaryhex': '#FF0000',
  'secondaryhex': '#009900',
  'team': 'SV Zulte Waregem'},
 {'id': 10,
  'primaryhex': '#FF6600',
  'secondaryhex': '#000000',
  'team': 'Ural Yekaterinburg'},
 {'id': 11,
  'primaryhex': '#33CCFF',
  'secondaryhex': '#FFFFFF',
  'team': 'Manchester City'},
 {'id': 12,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Fulham FC'},
 {'id': 13,
  'primaryhex': '#003a78',
  'secondaryhex': '#db0000',
  'team': 'FC Chiasso'},
 {'id': 14,
  'primaryhex': '#0066FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Queens Park Rangers'},
 {'id': 15,
  'primaryhex': '#00D1C7',
  'secondaryhex': '#000000',
  'team': 'Club Deportes Iquique'},
 {'id': 16,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Olympiacos Piraeus'},
 {'id': 17,
  'primaryhex': '#d62424',
  'secondaryhex': '#000000',
  'team': 'FK Macva Sabac'},
 {'id': 18,
  'primaryhex': '#0000a3',
  'secondaryhex': '#e3e312',
  'team': 'Oita Trinita'},
 {'id': 19,
  'primaryhex': '#089908',
  'secondaryhex': '#fcf803',
  'team': 'Fortuna Sittard'},
 {'id': 20,
  'primaryhex': '#1c388c',
  'secondaryhex': '#E32118',
  'team': 'GNK Dinamo Zagreb'},
 {'id': 21,
  'primaryhex': '#3399FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Málaga CF'},
 {'id': 22,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'LD Alajuelense'},
 {'id': 23,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'Terengganu FC'},
 {'id': 24,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Fleetwood Town'},
 {'id': 25,
  'primaryhex': '#81C0FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Malmö FF'},
 {'id': 26,
  'primaryhex': '#13007C',
  'secondaryhex': '#FFFFFF',
  'team': 'SV Meppen'},
 {'id': 27,
  'primaryhex': '#000000',
  'secondaryhex': '#158c43',
  'team': 'FK Krasnodar'},
 {'id': 28,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Phoenix Rising FC'},
 {'id': 29,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'AZ Alkmaar U21'},
 {'id': 30,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#032AF0',
  'team': 'Bury FC'},
 {'id': 31,
  'primaryhex': '#0000FF',
  'secondaryhex': '#ffffff',
  'team': 'Getafe CF'},
 {'id': 32,
  'primaryhex': '#d61a20',
  'secondaryhex': '#0a7d25',
  'team': 'Henan Jianye'},
 {'id': 33,
  'primaryhex': '#ed0909',
  'secondaryhex': '#483deb',
  'team': 'Bologna FC 1909'},
 {'id': 34,
  'primaryhex': '#80000A',
  'secondaryhex': '#221F1F',
  'team': 'Atlanta United FC'},
 {'id': 35,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#009900',
  'team': 'JEF United Chiba'},
 {'id': 36,
  'primaryhex': '#4F8A10',
  'secondaryhex': '#11568C',
  'team': 'Seattle Sounders FC'},
 {'id': 37,
  'primaryhex': '#f0ca0e',
  'secondaryhex': '#db0000',
  'team': 'Benevento Calcio'},
 {'id': 38,
  'primaryhex': '#d43333',
  'secondaryhex': '#1d0d61',
  'team': 'FC Crotone'},
 {'id': 39,
  'primaryhex': '#b50909',
  'secondaryhex': '#050505',
  'team': 'AC Milan'},
 {'id': 40,
  'primaryhex': '#008141',
  'secondaryhex': '#FFFFFF',
  'team': 'FC St. Gallen 1879'},
 {'id': 41,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Twente Enschede'},
 {'id': 42,
  'primaryhex': '#081d87',
  'secondaryhex': '#f00e0e',
  'team': 'Indy Eleven'},
 {'id': 43,
  'primaryhex': '#0ecc25',
  'secondaryhex': '#f5f500',
  'team': 'Yeovil Town'},
 {'id': 44,
  'primaryhex': '#FFFF33',
  'secondaryhex': '#CC0000',
  'team': 'Go Ahead Eagles Deventer'},
 {'id': 45,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#660099',
  'team': 'RSC Anderlecht'},
 {'id': 46,
  'primaryhex': '#ff0000',
  'secondaryhex': '#ffff00',
  'team': 'Semen Padang FC'},
 {'id': 47,
  'primaryhex': '#1ED433',
  'secondaryhex': '#F5E90A',
  'team': 'Lamontville Golden Arrows'},
 {'id': 48,
  'primaryhex': '#ff0000',
  'secondaryhex': '#fffcfc',
  'team': 'Atletico River Plate Montevideo'},
 {'id': 49,
  'primaryhex': '#00FF00',
  'secondaryhex': '#0000CC',
  'team': 'Shonan Bellmare'},
 {'id': 50,
  'primaryhex': '#0b05ad',
  'secondaryhex': '#000000',
  'team': 'Liverpool FC Montevideo'},
 {'id': 51,
  'primaryhex': '#E0E01B',
  'secondaryhex': '#1D03AD',
  'team': 'FK Dinamo Vranje'},
 {'id': 52,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'SL Benfica B'},
 {'id': 53,
  'primaryhex': '#ff0000',
  'secondaryhex': '#FFF700',
  'team': 'US Quevilly-Rouen Métropole'},
 {'id': 54,
  'primaryhex': '#FF6600',
  'secondaryhex': '#3300FF',
  'team': 'Albirex Niigata'},
 {'id': 55,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Rotherham United'},
 {'id': 56,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Bali United FC'},
 {'id': 57,
  'primaryhex': '#990000',
  'secondaryhex': '#FFFFFF',
  'team': 'Northampton Town'},
 {'id': 58,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Yeni Malatyaspor'},
 {'id': 59,
  'primaryhex': '#ff0000',
  'secondaryhex': '#000000',
  'team': 'Gyeongnam FC'},
 {'id': 60,
  'primaryhex': '#fcd217',
  'secondaryhex': '#000000',
  'team': 'Criciúma Esporte Clube'},
 {'id': 61,
  'primaryhex': '#ff0000',
  'secondaryhex': '#0000ff',
  'team': 'Olympique Lyon'},
 {'id': 62,
  'primaryhex': '#6796C6',
  'secondaryhex': '#FFFFFF',
  'team': 'SV Darmstadt 98'},
 {'id': 63,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'Santos FC'},
 {'id': 64,
  'primaryhex': '#3c9135',
  'secondaryhex': '#ffffff',
  'team': 'Akhmat Grozny'},
 {'id': 65,
  'primaryhex': '#007FFF',
  'secondaryhex': '#FFFFFF',
  'team': 'Brescia Calcio'},
 {'id': 66,
  'primaryhex': '#F20505',
  'secondaryhex': '#FFFFFF',
  'team': 'LOSC Lille'},
 {'id': 67,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0033CC',
  'team': 'KAA Gent'},
 {'id': 68,
  'primaryhex': '#614c99',
  'secondaryhex': '#ffffff',
  'team': 'ACF Fiorentina'},
 {'id': 69,
  'primaryhex': '#515ee8',
  'secondaryhex': '#f5ebeb',
  'team': 'UC Sampdoria'},
 {'id': 70,
  'primaryhex': '#ff0d0d',
  'secondaryhex': '#067a0a',
  'team': 'Club Atlético Boston River'},
 {'id': 71,
  'primaryhex': '#FF9900',
  'secondaryhex': '#FFFFFF',
  'team': 'FELDA United FC'},
 {'id': 72,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0A67B7',
  'team': 'CS Universitatea Craiova'},
 {'id': 73,
  'primaryhex': '#12264C',
  'secondaryhex': '#85B7EA',
  'team': 'Vancouver Whitecaps FC'},
 {'id': 74,
  'primaryhex': '#ff0000',
  'secondaryhex': '#f7ff00',
  'team': 'AS Lyon-Duchère'},
 {'id': 75,
  'primaryhex': '#D10019',
  'secondaryhex': '#000000',
  'team': 'FC Admira Wacker Mödling'},
 {'id': 76,
  'primaryhex': '#000000',
  'secondaryhex': '#C5F505',
  'team': 'Eastern Suburbs AFC'},
 {'id': 77,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'UD Las Palmas'},
 {'id': 78,
  'primaryhex': '#f8c300',
  'secondaryhex': '#262175',
  'team': 'Vegalta Sendai'},
 {'id': 79,
  'primaryhex': '#FF0000',
  'secondaryhex': '#050505',
  'team': 'SG Sonnenhof Großaspach'},
 {'id': 80,
  'primaryhex': '#0051BA',
  'secondaryhex': '#000000',
  'team': 'San Jose Earthquakes'},
 {'id': 81,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0404e0',
  'team': 'Tochigi SC'},
 {'id': 82,
  'primaryhex': '#080808',
  'secondaryhex': '#fffcfc',
  'team': 'Montevideo Wanderers'},
 {'id': 83,
  'primaryhex': '#02AD0D',
  'secondaryhex': '#F7FF08',
  'team': 'Kedah FA'},
 {'id': 84,
  'primaryhex': '#EE2690',
  'secondaryhex': '#ff0000',
  'team': 'Sai Gon FC'},
 {'id': 85,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFF00',
  'team': 'El Gouna FC'},
 {'id': 86,
  'primaryhex': '#0d6302',
  'secondaryhex': '#e3e310',
  'team': 'Portland Timbers 2'},
 {'id': 87,
  'primaryhex': '#004CFF',
  'secondaryhex': '#FFFFFF',
  'team': 'Hertha BSC'},
 {'id': 88,
  'primaryhex': '#000000',
  'secondaryhex': '#f70000',
  'team': 'SBV Excelsior Rotterdam'},
 {'id': 89,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Arab Contractors SC'},
 {'id': 90,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FSV Zwickau'},
 {'id': 91,
  'primaryhex': '#FFEA00',
  'secondaryhex': '#000000',
  'team': 'Perak TBG FC'},
 {'id': 92,
  'primaryhex': '#006',
  'secondaryhex': '#FDFDFD',
  'team': 'Buriram United'},
 {'id': 93,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Accrington Stanley'},
 {'id': 94,
  'primaryhex': '#170ce8',
  'secondaryhex': '#000000',
  'team': 'FK Nizhny Novgorod'},
 {'id': 95,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFF00',
  'team': 'Club Atlético Rosario Central'},
 {'id': 96,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Stevenage FC'},
 {'id': 97,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#003300',
  'team': 'Tom Tomsk'},
 {'id': 98,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'JS Kairouanaise'},
 {'id': 99,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Piast Gliwice'},
 {'id': 100,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Rangers FC'},
 {'id': 101,
  'primaryhex': '#000000',
  'secondaryhex': '#C4161C',
  'team': 'SV Wehen Wiesbaden'},
 {'id': 102,
  'primaryhex': '#1828db',
  'secondaryhex': '#e3e019',
  'team': 'Pars Jonoubi Jam'},
 {'id': 103,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFAA00',
  'team': 'Persija Jakarta'},
 {'id': 104,
  'primaryhex': '#0e2ae6',
  'secondaryhex': '#f20909',
  'team': 'AD Union Magdalena'},
 {'id': 105,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'Córdoba CF'},
 {'id': 106,
  'primaryhex': '#006EB7',
  'secondaryhex': '#FFFEFF',
  'team': 'FC Lausanne-Sport'},
 {'id': 107,
  'primaryhex': '#0071bd',
  'secondaryhex': '#fad000',
  'team': 'Jiangsu Suning'},
 {'id': 108,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Dagenham &amp; Redbridge FC'},
 {'id': 109,
  'primaryhex': '#CC0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Willem II Tilburg'},
 {'id': 110,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Club Atlético San Lorenzo de Almagro'},
 {'id': 111,
  'primaryhex': '#F36600',
  'secondaryhex': '#2E2926',
  'team': 'Houston Dynamo'},
 {'id': 112,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#ff0000',
  'team': 'Milton Keynes Dons'},
 {'id': 113,
  'primaryhex': '#f50a0a',
  'secondaryhex': '#000000',
  'team': 'FK Khimki'},
 {'id': 114,
  'primaryhex': '#FF0033',
  'secondaryhex': '#FFFFFF',
  'team': 'Southampton FC'},
 {'id': 115,
  'primaryhex': '#000000',
  'secondaryhex': '#c4acac',
  'team': 'San Antonio FC'},
 {'id': 116,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#173880',
  'team': 'Real Madrid'},
 {'id': 117,
  'primaryhex': '#339900',
  'secondaryhex': '#FFFFFF',
  'team': 'Karpaty Lviv'},
 {'id': 118,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Borussia Mönchengladbach'},
 {'id': 119,
  'primaryhex': '#FDF105',
  'secondaryhex': '#000000',
  'team': 'Borussia Dortmund'},
 {'id': 120,
  'primaryhex': '#FF6F00',
  'secondaryhex': '#001EFF',
  'team': 'Olympique de Médéa'},
 {'id': 121,
  'primaryhex': '#2EE612',
  'secondaryhex': '#EDF508',
  'team': 'Baroka FC'},
 {'id': 122,
  'primaryhex': '#000fb3',
  'secondaryhex': '#e3ff0d',
  'team': 'CD Everton'},
 {'id': 123,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Chornomorets Odessa'},
 {'id': 124,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'PAOK Thessaloniki'},
 {'id': 125,
  'primaryhex': '#681938',
  'secondaryhex': '#2DB2EB',
  'team': 'Trabzonspor'},
 {'id': 126,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'SL Benfica'},
 {'id': 127,
  'primaryhex': '#facdee',
  'secondaryhex': '#0a0a0a',
  'team': 'US Palermo'},
 {'id': 128,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'VfR Aalen'},
 {'id': 129,
  'primaryhex': '#0000FF',
  'secondaryhex': '#000000',
  'team': 'FC Viitorul '},
 {'id': 130,
  'primaryhex': '#FF0D0D',
  'secondaryhex': '#FFFFFF',
  'team': 'Sparta Rotterdam'},
 {'id': 131,
  'primaryhex': '#130080',
  'secondaryhex': '#FD44A0',
  'team': 'Independiente del Valle'},
 {'id': 132,
  'primaryhex': '#0F5787',
  'secondaryhex': '#FFFFFF',
  'team': 'Holstein Kiel'},
 {'id': 133,
  'primaryhex': '#808080',
  'secondaryhex': '#ff0000',
  'team': 'US Cremonese'},
 {'id': 134,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Atlas Guadalajara'},
 {'id': 135,
  'primaryhex': '#00003d',
  'secondaryhex': '#730000',
  'team': 'Pogon Szczecin'},
 {'id': 136,
  'primaryhex': '#FFDE05',
  'secondaryhex': '#000000',
  'team': 'Club Athlétique Bizertin'},
 {'id': 137,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Royal Excel Mouscron '},
 {'id': 138,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Arminia Bielefeld'},
 {'id': 139,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Cracovia Kraków'},
 {'id': 140,
  'primaryhex': '#ff0000',
  'secondaryhex': '#000000',
  'team': 'FC Pohang Steelers'},
 {'id': 141,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Utrecht'},
 {'id': 142,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Cheltenham Town'},
 {'id': 143,
  'primaryhex': '#050505',
  'secondaryhex': '#fafafa',
  'team': 'Ceará Sporting Club'},
 {'id': 144,
  'primaryhex': '#ad0000',
  'secondaryhex': '#000000',
  'team': 'Atlanta United 2'},
 {'id': 145,
  'primaryhex': '#000000',
  'secondaryhex': '#ff0000',
  'team': 'Neuchâtel Xamax FCS'},
 {'id': 146,
  'primaryhex': '#067009',
  'secondaryhex': '#FCF9F9',
  'team': 'Racing Club de Montevideo'},
 {'id': 147,
  'primaryhex': '#ff8800',
  'secondaryhex': '#008800',
  'team': 'Gangwon FC'},
 {'id': 148,
  'primaryhex': '#080808',
  'secondaryhex': '#FFFFFF',
  'team': 'Botafogo Rio de Janeiro'},
 {'id': 149,
  'primaryhex': '#0033CC',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Hansa Rostock'},
 {'id': 150,
  'primaryhex': '#4156D1',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Edmonton'},
 {'id': 151,
  'primaryhex': '#0000CC',
  'secondaryhex': '#CC0000',
  'team': 'FC Barcelona'},
 {'id': 152,
  'primaryhex': '#FF9D00',
  'secondaryhex': '#003099',
  'team': 'FC Cincinnati'},
 {'id': 153,
  'primaryhex': '#025FAC',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Schalke 04'},
 {'id': 154,
  'primaryhex': '#ff0011',
  'secondaryhex': '#ffffff',
  'team': 'Hebei China Fortune'},
 {'id': 155,
  'primaryhex': '#731cad',
  'secondaryhex': '#f7f2f2',
  'team': 'CA Fénix'},
 {'id': 156,
  'primaryhex': '#F5B803',
  'secondaryhex': '#1B48B8',
  'team': 'Mansfield Town'},
 {'id': 157,
  'primaryhex': '#FFD500',
  'secondaryhex': '#DB0000',
  'team': 'Jagiellonia Bialystok'},
 {'id': 158,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Asociación Atlética Argentinos Juniors'},
 {'id': 159,
  'primaryhex': '#07078a',
  'secondaryhex': '#e60707',
  'team': 'Genoa CFC'},
 {'id': 160,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'St. Mirren FC'},
 {'id': 161,
  'primaryhex': '#0000CC',
  'secondaryhex': '#CC0000',
  'team': 'Levante UD'},
 {'id': 162,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Arsenal FC'},
 {'id': 163,
  'primaryhex': '#008543',
  'secondaryhex': '#FFFFFF',
  'team': 'Rapid Vienna'},
 {'id': 164,
  'primaryhex': '#3399FF',
  'secondaryhex': '#FF33CC',
  'team': 'Sagan Tosu'},
 {'id': 165,
  'primaryhex': '#000000',
  'secondaryhex': '#0055A0',
  'team': 'Inter Milan'},
 {'id': 166,
  'primaryhex': '#5D6FE3',
  'secondaryhex': '#000000',
  'team': 'Paykan FC'},
 {'id': 167,
  'primaryhex': '#0d19ba',
  'secondaryhex': '#ffffff',
  'team': 'FK Orenburg'},
 {'id': 168,
  'primaryhex': '#e01212',
  'secondaryhex': '#0707e0',
  'team': 'SD Eibar'},
 {'id': 169,
  'primaryhex': '#E40019',
  'secondaryhex': '#FFFFFF',
  'team': '1.FC Union Berlin'},
 {'id': 170,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0033CC',
  'team': 'RKC Waalwijk'},
 {'id': 171,
  'primaryhex': '#0D258F',
  'secondaryhex': '#000000',
  'team': '1.FC Slovácko'},
 {'id': 172,
  'primaryhex': '#a60303',
  'secondaryhex': '#23158c',
  'team': 'Cosenza Calcio'},
 {'id': 173,
  'primaryhex': '#ff0000',
  'secondaryhex': '#1900d9',
  'team': 'Deportivo Guadalajara'},
 {'id': 174,
  'primaryhex': '#00245D',
  'secondaryhex': '#F1AA00',
  'team': 'Los Angeles Galaxy'},
 {'id': 175,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'Bursaspor'},
 {'id': 176,
  'primaryhex': '#ffea00',
  'secondaryhex': '#000000',
  'team': 'VVV-Venlo'},
 {'id': 177,
  'primaryhex': '#0037eb',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Porto'},
 {'id': 178,
  'primaryhex': '#0000FF',
  'secondaryhex': '#000000',
  'team': 'Rochdale AFC'},
 {'id': 179,
  'primaryhex': '#FF9900',
  'secondaryhex': '#FFFFFF',
  'team': 'Istanbul Basaksehir FK'},
 {'id': 180,
  'primaryhex': '#050405',
  'secondaryhex': '#FFFFFF',
  'team': 'Sport Club Corinthians Paulista'},
 {'id': 181,
  'primaryhex': '#0000CC',
  'secondaryhex': '#FFFF00',
  'team': 'Southern United'},
 {'id': 182,
  'primaryhex': '#FF0000',
  'secondaryhex': '#00A800',
  'team': 'USM Bel Abbès'},
 {'id': 183,
  'primaryhex': '#000979',
  'secondaryhex': '#FF0000',
  'team': 'Paris Saint-Germain'},
 {'id': 184,
  'primaryhex': '#9900CC',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Erzgebirge Aue'},
 {'id': 185,
  'primaryhex': '#000080',
  'secondaryhex': '#FFFFFF',
  'team': 'West Bromwich Albion'},
 {'id': 186,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'RSC Charleroi'},
 {'id': 187,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Chesterfield FC'},
 {'id': 188,
  'primaryhex': '#66CC00',
  'secondaryhex': '#FFFFFF',
  'team': 'VfL Wolfsburg'},
 {'id': 189,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Standard Liège'},
 {'id': 190,
  'primaryhex': '#0099FF',
  'secondaryhex': '#003399',
  'team': 'Wycombe Wanderers'},
 {'id': 191,
  'primaryhex': '#003B79',
  'secondaryhex': '#E2001A',
  'team': '1.FC Heidenheim 1846'},
 {'id': 192,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Utrecht U21'},
 {'id': 193,
  'primaryhex': '#002db5',
  'secondaryhex': '#000000',
  'team': 'Huachipato FC'},
 {'id': 194,
  'primaryhex': '#3BBD68',
  'secondaryhex': '#ffffff',
  'team': 'Atlético Nacional'},
 {'id': 195,
  'primaryhex': '#8a8282',
  'secondaryhex': '#ad0707',
  'team': 'Colorado Springs Switchbacks FC'},
 {'id': 196,
  'primaryhex': '#fa2d2d',
  'secondaryhex': '#030303',
  'team': 'FK Napredak Krusevac'},
 {'id': 197,
  'primaryhex': '#0000ff',
  'secondaryhex': '#000000',
  'team': 'Gamba Osaka'},
 {'id': 198,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Spartak 2 Moscow'},
 {'id': 199,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Thanh Hoa FC'},
 {'id': 200,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#00CCFF',
  'team': 'Club Atlético Tucumán'},
 {'id': 201,
  'primaryhex': '#fffb00',
  'secondaryhex': '#0091ff',
  'team': 'Bröndby IF'},
 {'id': 202,
  'primaryhex': '#99CCFF',
  'secondaryhex': '#FFFFFF',
  'team': 'Celta de Vigo'},
 {'id': 203,
  'primaryhex': '#bd0b0b',
  'secondaryhex': '#000000',
  'team': 'Foggia Calcio'},
 {'id': 204,
  'primaryhex': '#009900',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Groningen'},
 {'id': 205,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000066',
  'team': 'Olympique Safi'},
 {'id': 206,
  'primaryhex': '#F5A12D',
  'secondaryhex': '#000000',
  'team': 'Hull City'},
 {'id': 207,
  'primaryhex': '#009900',
  'secondaryhex': '#FFFF00',
  'team': 'Club León FC'},
 {'id': 208,
  'primaryhex': '#FAFAFA',
  'secondaryhex': '#2AA8EB',
  'team': 'Chippa United'},
 {'id': 209,
  'primaryhex': '#CF0032',
  'secondaryhex': '#07175C',
  'team': 'FC Dallas'},
 {'id': 210,
  'primaryhex': '#ba1111',
  'secondaryhex': '#1c41d6',
  'team': 'SpVgg Unterhaching'},
 {'id': 211,
  'primaryhex': '#ff0000',
  'secondaryhex': '#000000',
  'team': 'Persipura Jayapura'},
 {'id': 212,
  'primaryhex': '#00803C',
  'secondaryhex': '#FFFFFF',
  'team': 'TIRA-Persikabo'},
 {'id': 213,
  'primaryhex': '#ffff00',
  'secondaryhex': '#000000',
  'team': 'AEK Athens'},
 {'id': 214,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Club Tijuana'},
 {'id': 215,
  'primaryhex': '#1E90FF',
  'secondaryhex': '#FFFF00',
  'team': 'Sanna Khanh Hoa Bien Viet Nam FC'},
 {'id': 216,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'SC Rheindorf Altach'},
 {'id': 217,
  'primaryhex': '#0A1DF5',
  'secondaryhex': '#FADA0A',
  'team': 'Cape Town City FC '},
 {'id': 218,
  'primaryhex': '#ffd000',
  'secondaryhex': '#000000',
  'team': 'Fuerza Amarilla SC'},
 {'id': 219,
  'primaryhex': '#ffff00',
  'secondaryhex': '#880088',
  'team': 'Jeonnam Dragons FC'},
 {'id': 220,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Sint-Truidense VV'},
 {'id': 221,
  'primaryhex': '#FF6600',
  'secondaryhex': '#000000',
  'team': 'Renaissance de Berkane'},
 {'id': 222,
  'primaryhex': '#91022D',
  'secondaryhex': '#85B7EA',
  'team': 'Colorado Rapids'},
 {'id': 223,
  'primaryhex': '#ff0000',
  'secondaryhex': '#000000',
  'team': 'Sangju Sangmu FC'},
 {'id': 224,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Waitakere United'},
 {'id': 225,
  'primaryhex': '#edf500',
  'secondaryhex': '#1e00ff',
  'team': 'Universidad Concepción'},
 {'id': 226,
  'primaryhex': '#0F57D4',
  'secondaryhex': '#FAF7F7',
  'team': 'Maritzburg United FC'},
 {'id': 227,
  'primaryhex': '#8a0707',
  'secondaryhex': '#000000',
  'team': 'Lokomotiv Plovdiv'},
 {'id': 228,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'CD El Nacional'},
 {'id': 229,
  'primaryhex': '#050505',
  'secondaryhex': '#fffcfc',
  'team': 'Danubio FC'},
 {'id': 230,
  'primaryhex': '#0044FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Bengaluru FC'},
 {'id': 231,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Madura United FC'},
 {'id': 232,
  'primaryhex': '#018202',
  'secondaryhex': '#FFFFFF',
  'team': 'SV Mattersburg'},
 {'id': 233,
  'primaryhex': '#187A2F',
  'secondaryhex': '#042FBF',
  'team': 'Caykur Rizespor'},
 {'id': 234,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Club Atlético River Plate'},
 {'id': 235,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Botev Plovdiv'},
 {'id': 236,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'CD Leganés'},
 {'id': 237,
  'primaryhex': '#441678',
  'secondaryhex': '#FFFFFF',
  'team': 'Austria Vienna'},
 {'id': 238,
  'primaryhex': '#25910A',
  'secondaryhex': '#253EA1',
  'team': 'Tacoma Defiance'},
 {'id': 239,
  'primaryhex': '#ff0000',
  'secondaryhex': '#168500',
  'team': 'Zaglebie Sosnowiec'},
 {'id': 240,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Southend United'},
 {'id': 241,
  'primaryhex': '#FF0000',
  'secondaryhex': '#ffffff',
  'team': 'Aberdeen FC'},
 {'id': 242,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Esporte Clube Bahia'},
 {'id': 243,
  'primaryhex': '#8B4513',
  'secondaryhex': '#FFFFFF',
  'team': 'FC St. Pauli'},
 {'id': 244,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Hamilton Academical FC'},
 {'id': 245,
  'primaryhex': '#FDB913',
  'secondaryhex': '#231F20',
  'team': 'Wolverhampton Wanderers'},
 {'id': 246,
  'primaryhex': '#0000FF',
  'secondaryhex': '#00FFFF',
  'team': 'Rotor Volgograd'},
 {'id': 247,
  'primaryhex': '#fff200',
  'secondaryhex': '#00b6d6',
  'team': 'FC Astana'},
 {'id': 248,
  'primaryhex': '#E80C06',
  'secondaryhex': '#FFFFFF',
  'team': 'Ho Chi Minh City'},
 {'id': 249,
  'primaryhex': '#E41349',
  'secondaryhex': '#FFFFFF',
  'team': 'Red Bull Salzburg'},
 {'id': 250,
  'primaryhex': '#154281',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Luzern'},
 {'id': 251,
  'primaryhex': '#fa8508',
  'secondaryhex': '#1809b5',
  'team': 'Tulsa Roughnecks FC'},
 {'id': 252,
  'primaryhex': '#ED1C23',
  'secondaryhex': '#FFFFFF',
  'team': '1. FC Köln'},
 {'id': 253,
  'primaryhex': '#CC0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Club Necaxa'},
 {'id': 254,
  'primaryhex': '#000099',
  'secondaryhex': '#CC0033',
  'team': "Johor Darul Ta'zim FC"},
 {'id': 255,
  'primaryhex': '#0404D3',
  'secondaryhex': '#E2E2E2',
  'team': 'CS Emelec'},
 {'id': 256,
  'primaryhex': '#CC0000',
  'secondaryhex': '#FFFFFF',
  'team': 'CFR Cluj'},
 {'id': 257,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Rayo Vallecano'},
 {'id': 258,
  'primaryhex': '#E80C38',
  'secondaryhex': '#FFFFFF',
  'team': 'Bayern Munich'},
 {'id': 259,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Hallescher FC'},
 {'id': 260,
  'primaryhex': '#000080',
  'secondaryhex': '#FFD700',
  'team': 'Bethlehem Steel FC'},
 {'id': 261,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'Port Vale FC'},
 {'id': 262,
  'primaryhex': '#000066',
  'secondaryhex': '#CCCCCC',
  'team': 'Avispa Fukuoka'},
 {'id': 263,
  'primaryhex': '#B3040C',
  'secondaryhex': '#FFFFFF',
  'team': 'CSKA Sofia'},
 {'id': 264,
  'primaryhex': '#0D6ECD',
  'secondaryhex': '#FFFFFF',
  'team': 'Pyramids FC'},
 {'id': 265,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'VfB Stuttgart'},
 {'id': 266,
  'primaryhex': '#2B579E',
  'secondaryhex': '#FFFFFF',
  'team': 'VfL Bochum'},
 {'id': 267,
  'primaryhex': '#cc0000',
  'secondaryhex': '#000000',
  'team': 'Bucheon FC 1995'},
 {'id': 268,
  'primaryhex': '#0033CC',
  'secondaryhex': '#FFFFFF',
  'team': 'TSG 1899 Hoffenheim'},
 {'id': 269,
  'primaryhex': '#004812',
  'secondaryhex': '#EBE72B',
  'team': 'Portland Timbers'},
 {'id': 270,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Burton Albion'},
 {'id': 271,
  'primaryhex': '#000979',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Girondins Bordeaux'},
 {'id': 272,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Kawkab Marrakech'},
 {'id': 273,
  'primaryhex': '#633492',
  'secondaryhex': '#FF6600',
  'team': 'Perth Glory'},
 {'id': 274,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Heracles Almelo'},
 {'id': 275,
  'primaryhex': '#ED1C23',
  'secondaryhex': '#FFFFFF',
  'team': 'PSV Eindhoven'},
 {'id': 276,
  'primaryhex': '#FCFCFC',
  'secondaryhex': '#0A0909',
  'team': 'Juventus FC'},
 {'id': 277,
  'primaryhex': '#290EF5',
  'secondaryhex': '#FFFFFF',
  'team': 'SuperSport United'},
 {'id': 278,
  'primaryhex': '#0000CC',
  'secondaryhex': '#FFFFFF',
  'team': 'SC Heerenveen'},
 {'id': 279,
  'primaryhex': '#D50031',
  'secondaryhex': '#012055',
  'team': 'New York Red Bulls'},
 {'id': 280,
  'primaryhex': '#fffb00',
  'secondaryhex': '#0000ff',
  'team': 'Parma Calcio 1913'},
 {'id': 281,
  'primaryhex': '#0072CE',
  'secondaryhex': '#FFFFFF',
  'team': 'Huddersfield Town'},
 {'id': 282,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Sepsi Sf. Gheorghe'},
 {'id': 283,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Tractor Sazi FC'},
 {'id': 284,
  'primaryhex': '#F50505',
  'secondaryhex': '#FFFCFC',
  'team': '1.FC Kaiserslautern'},
 {'id': 285,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Hawke’s Bay United'},
 {'id': 286,
  'primaryhex': '#FC0000',
  'secondaryhex': '#000000',
  'team': 'Clube de Regatas do Flamengo'},
 {'id': 287,
  'primaryhex': '#0035BA',
  'secondaryhex': '#FFFFFF',
  'team': 'Chertanovo Moscow'},
 {'id': 288,
  'primaryhex': '#000066',
  'secondaryhex': '#F7FF00',
  'team': 'MKE Ankaragücü'},
 {'id': 289,
  'primaryhex': '#335525',
  'secondaryhex': '#FFFFFF',
  'team': 'Cavalry FC'},
 {'id': 290,
  'primaryhex': '#e0e316',
  'secondaryhex': '#0011ff',
  'team': 'FK Rostov'},
 {'id': 291,
  'primaryhex': '#FF0808',
  'secondaryhex': '#000000',
  'team': 'Caracas FC'},
 {'id': 292,
  'primaryhex': '#1a1970',
  'secondaryhex': '#BD2031',
  'team': 'North Carolina FC'},
 {'id': 293,
  'primaryhex': '#660808',
  'secondaryhex': '#73e8f0',
  'team': 'Burnley FC'},
 {'id': 294,
  'primaryhex': '#FF1433',
  'secondaryhex': '#004093',
  'team': 'FC Basel 1893'},
 {'id': 295,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000066',
  'team': 'Fenerbahce SK'},
 {'id': 296,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Wolfsberger AC'},
 {'id': 297,
  'primaryhex': '#12b2c7',
  'secondaryhex': '#f7ff00',
  'team': "CD O'Higgins"},
 {'id': 298,
  'primaryhex': '#0e00cf',
  'secondaryhex': '#fffcfc',
  'team': 'Juventud de Las Piedras'},
 {'id': 299,
  'primaryhex': '#FAFA00',
  'secondaryhex': '#000000',
  'team': 'Barcelona SC Guayaquil'},
 {'id': 300,
  'primaryhex': '#FFCC00',
  'secondaryhex': '#660033',
  'team': 'Motherwell FC'},
 {'id': 301,
  'primaryhex': '#e1ff00',
  'secondaryhex': '#226b05',
  'team': 'CD Tondela'},
 {'id': 302,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Arka Gdynia'},
 {'id': 303,
  'primaryhex': '#004B92',
  'secondaryhex': '#FFFFFF',
  'team': 'Lech Poznan'},
 {'id': 304,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Wadi Degla FC'},
 {'id': 305,
  'primaryhex': '#282496',
  'secondaryhex': '#8c1919',
  'team': 'Real Monarchs SLC'},
 {'id': 306,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Zamalek SC'},
 {'id': 307,
  'primaryhex': '#ffd940',
  'secondaryhex': '#000002',
  'team': 'BSC Young Boys'},
 {'id': 308,
  'primaryhex': '#ffdd00',
  'secondaryhex': '#004393',
  'team': 'Frosinone Calcio'},
 {'id': 309,
  'primaryhex': '#003399',
  'secondaryhex': '#000000',
  'team': 'Enppi Club'},
 {'id': 310,
  'primaryhex': '#F00000',
  'secondaryhex': '#0021F5',
  'team': 'FK Radnicki Nis'},
 {'id': 311,
  'primaryhex': '#00bfff',
  'secondaryhex': '#FDFDFB',
  'team': 'FC Zürich'},
 {'id': 312,
  'primaryhex': '#000000',
  'secondaryhex': '#00703C',
  'team': 'FC Wacker Innsbruck'},
 {'id': 313,
  'primaryhex': '#C70202',
  'secondaryhex': '#000000',
  'team': 'USM Alger'},
 {'id': 314,
  'primaryhex': '#E00732',
  'secondaryhex': '#0B14BF',
  'team': 'Petrojet'},
 {'id': 315,
  'primaryhex': '#000000',
  'secondaryhex': '#006B00',
  'team': 'CS Constantine'},
 {'id': 316,
  'primaryhex': '#FF0000',
  'secondaryhex': '#006633',
  'team': 'NEC Nijmegen'},
 {'id': 317,
  'primaryhex': '#ffaa00',
  'secondaryhex': '#000000',
  'team': 'Perseru Badak Lampung FC'},
 {'id': 318,
  'primaryhex': '#f0e913',
  'secondaryhex': '#1000f7',
  'team': 'SC Cambuur-Leeuwarden'},
 {'id': 319,
  'primaryhex': '#e3b912',
  'secondaryhex': '#000000',
  'team': 'Pittsburgh Riverhounds SC'},
 {'id': 320,
  'primaryhex': '#4cba02',
  'secondaryhex': '#030303',
  'team': 'Forest Green Rovers '},
 {'id': 321,
  'primaryhex': '#FF66CC',
  'secondaryhex': '#330099',
  'team': 'Cerezo Osaka'},
 {'id': 322,
  'primaryhex': '#DE0000',
  'secondaryhex': '#004705',
  'team': 'Rampla Juniors FC'},
 {'id': 323,
  'primaryhex': '#0000ff',
  'secondaryhex': '#ff8800',
  'team': 'Ulsan Hyundai'},
 {'id': 324,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': "AS Aïn M'lila"},
 {'id': 325,
  'primaryhex': '#ffff00',
  'secondaryhex': '#000000',
  'team': 'PS Barito Putera'},
 {'id': 326,
  'primaryhex': '#0033CC',
  'secondaryhex': '#FFFFFF',
  'team': 'Querétaro FC'},
 {'id': 327,
  'primaryhex': '#0033ff',
  'secondaryhex': '#000000',
  'team': 'Incheon United FC'},
 {'id': 328,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Gillingham FC'},
 {'id': 329,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'FBC Melgar'},
 {'id': 330,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': "Hassania d'Agadir"},
 {'id': 331,
  'primaryhex': '#fae528',
  'secondaryhex': '#154abd',
  'team': 'Delfín SC'},
 {'id': 332,
  'primaryhex': '#008f4c',
  'secondaryhex': '#fff200',
  'team': 'Beijing Sinobo Guoan'},
 {'id': 333,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFF00',
  'team': 'AFC Wimbledon'},
 {'id': 334,
  'primaryhex': '#FF0000',
  'secondaryhex': '#030303',
  'team': 'Morecambe FC'},
 {'id': 335,
  'primaryhex': '#eb172c',
  'secondaryhex': '#FFFFFF',
  'team': 'Sunderland AFC'},
 {'id': 336,
  'primaryhex': '#000000',
  'secondaryhex': '#CCFF00',
  'team': 'CA Peñarol'},
 {'id': 337,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Aldershot Town'},
 {'id': 338,
  'primaryhex': '#00C4FF',
  'secondaryhex': '#0019D4',
  'team': 'Minerva Punjab FC'},
 {'id': 339,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'NorthEast United FC'},
 {'id': 340,
  'primaryhex': '#FAFAFA',
  'secondaryhex': '#030000',
  'team': 'Ascoli Calcio'},
 {'id': 341,
  'primaryhex': '#8CCDFF',
  'secondaryhex': '#FFFFFF',
  'team': 'CD Universidad Católica'},
 {'id': 342,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'Astra Giurgiu'},
 {'id': 343,
  'primaryhex': '#ff0000',
  'secondaryhex': '#f7ff00',
  'team': 'Arsenal Tula'},
 {'id': 344,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Livingston FC'},
 {'id': 345,
  'primaryhex': '#bd1313',
  'secondaryhex': '#730a0a',
  'team': 'Sacramento Republic FC'},
 {'id': 346,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Dinamo Bukarest'},
 {'id': 347,
  'primaryhex': '#FF0000',
  'secondaryhex': '#1724B5',
  'team': 'Deportivo Cuenca'},
 {'id': 348,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Club Atlético Patronato'},
 {'id': 349,
  'primaryhex': '#004FED',
  'secondaryhex': '#FF0000',
  'team': 'KFC Uerdingen 05'},
 {'id': 350,
  'primaryhex': '#FC3A3A',
  'secondaryhex': '#EAF520',
  'team': 'Rodez AF'},
 {'id': 351,
  'primaryhex': '#f2e63a',
  'secondaryhex': '#5338de',
  'team': 'Hellas Verona'},
 {'id': 352,
  'primaryhex': '#9e1414',
  'secondaryhex': '#000000',
  'team': 'FC Penafiel'},
 {'id': 353,
  'primaryhex': '#00CCCC',
  'secondaryhex': '#FFFFFF',
  'team': 'Puebla FC'},
 {'id': 354,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0d82db',
  'team': 'Nogoom FC'},
 {'id': 355,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'SSV Jahn Regensburg'},
 {'id': 356,
  'primaryhex': '#0066FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Real Oviedo'},
 {'id': 357,
  'primaryhex': '#82AFD9',
  'secondaryhex': '#2E3548',
  'team': 'El Paso Locomotive FC'},
 {'id': 358,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'SV Werder Bremen'},
 {'id': 359,
  'primaryhex': '#0052cc',
  'secondaryhex': '#FFFFFF',
  'team': 'Everton FC'},
 {'id': 360,
  'primaryhex': '#287a3b',
  'secondaryhex': '#130b70',
  'team': 'Saint Louis FC'},
 {'id': 361,
  'primaryhex': '#FF9900',
  'secondaryhex': '#000000',
  'team': 'FC Volendam'},
 {'id': 362,
  'primaryhex': '#A50531',
  'secondaryhex': '#013474',
  'team': 'Real Salt Lake City'},
 {'id': 363,
  'primaryhex': '#1B458F',
  'secondaryhex': '#C4122E',
  'team': 'Crystal Palace'},
 {'id': 364,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0000FF',
  'team': 'KRC Genk'},
 {'id': 365,
  'primaryhex': '#1F47BF',
  'secondaryhex': '#FFFFFF',
  'team': 'Carlisle United'},
 {'id': 366,
  'primaryhex': '#122089',
  'secondaryhex': '#000000',
  'team': 'Montreal Impact'},
 {'id': 367,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0073ff',
  'team': 'Villarreal CF'},
 {'id': 368,
  'primaryhex': '#000000',
  'secondaryhex': '#f7ff00',
  'team': 'FC Chambly'},
 {'id': 369,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFF00',
  'team': 'ADO Den Haag'},
 {'id': 370,
  'primaryhex': '#0099FF',
  'secondaryhex': '#0066FF',
  'team': 'Baniyas SC'},
 {'id': 371,
  'primaryhex': '#0015ff',
  'secondaryhex': '#ff0000',
  'team': 'Arema FC'},
 {'id': 372,
  'primaryhex': '#ff8000',
  'secondaryhex': '#000000',
  'team': 'Venezia FC'},
 {'id': 373,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Würzburger Kickers'},
 {'id': 374,
  'primaryhex': '#0CA32F',
  'secondaryhex': '#FCFCFC',
  'team': 'Bloemfontein Celtic'},
 {'id': 375,
  'primaryhex': '#ffd500',
  'secondaryhex': '#000000',
  'team': 'FC Schaffhausen'},
 {'id': 376,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Zenit St. Petersburg'},
 {'id': 377,
  'primaryhex': '#00CCFF',
  'secondaryhex': '#0000FF',
  'team': 'Yokohama FC'},
 {'id': 378,
  'primaryhex': '#fcf232',
  'secondaryhex': '#000000',
  'team': 'Charleston Battery'},
 {'id': 379,
  'primaryhex': '#993333',
  'secondaryhex': '#000088',
  'team': 'Daejeon Citizen FC'},
 {'id': 380,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Energie Cottbus'},
 {'id': 381,
  'primaryhex': '#fff200',
  'secondaryhex': '#0088ff',
  'team': 'Pakhtakor Tashkent'},
 {'id': 382,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Oxford United'},
 {'id': 383,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'MC Oran'},
 {'id': 384,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFFF',
  'team': 'Sociedade Esportiva Palmeiras'},
 {'id': 385,
  'primaryhex': '#042fdb',
  'secondaryhex': '#fff7f7',
  'team': 'Cerro Largo FC'},
 {'id': 386,
  'primaryhex': '#009932',
  'secondaryhex': '#FFFFFF',
  'team': 'Hannover 96'},
 {'id': 387,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'SG Dynamo Dresden'},
 {'id': 388,
  'primaryhex': '#aa0000',
  'secondaryhex': '#000088',
  'team': 'Suwon FC'},
 {'id': 389,
  'primaryhex': '#0064B9',
  'secondaryhex': '#FDFDFB',
  'team': 'Grasshopper Club Zurich'},
 {'id': 390,
  'primaryhex': '#0a0909',
  'secondaryhex': '#264deb',
  'team': 'Atalanta BC'},
 {'id': 391,
  'primaryhex': '#733737',
  'secondaryhex': '#9e822e',
  'team': 'FC Ryukyu'},
 {'id': 392,
  'primaryhex': '#0026ff',
  'secondaryhex': '#ff0000',
  'team': 'US Concarneau'},
 {'id': 393,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#084BF5',
  'team': 'Tranmere Rovers'},
 {'id': 394,
  'primaryhex': '#fff200',
  'secondaryhex': '#f20303',
  'team': 'Korona Kielce'},
 {'id': 395,
  'primaryhex': '#FFEE00',
  'secondaryhex': '#00B831',
  'team': 'JS Saoura'},
 {'id': 396,
  'primaryhex': '#F0EB9A',
  'secondaryhex': '#000099',
  'team': 'CF América'},
 {'id': 397,
  'primaryhex': '#F7FF00',
  'secondaryhex': '#0048FF',
  'team': 'Pahang FA'},
 {'id': 398,
  'primaryhex': '#FF0033',
  'secondaryhex': '#FFFFFF',
  'team': 'Stoke City'},
 {'id': 399,
  'primaryhex': '#000f96',
  'secondaryhex': '#ffff00',
  'team': 'Pau FC'},
 {'id': 400,
  'primaryhex': '#A4BBD7',
  'secondaryhex': '#0a1f3d',
  'team': 'Swope Park Rangers'},
 {'id': 401,
  'primaryhex': '#000000',
  'secondaryhex': '#C4A465',
  'team': 'Los Angeles FC'},
 {'id': 402,
  'primaryhex': '#6aacdf',
  'secondaryhex': '#CD1024',
  'team': 'Melbourne City FC'},
 {'id': 403,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Zweigen Kanazawa'},
 {'id': 404,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Botosani'},
 {'id': 405,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Gaz Metan Medias'},
 {'id': 406,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFFF',
  'team': 'Vorskla Poltava'},
 {'id': 407,
  'primaryhex': '#F58B0A',
  'secondaryhex': '#0A0A0A',
  'team': 'Polokwane City FC'},
 {'id': 408,
  'primaryhex': '#001B2D',
  'secondaryhex': '#B18500',
  'team': 'Philadelphia Union'},
 {'id': 409,
  'primaryhex': '#004793',
  'secondaryhex': '#FFFFFF',
  'team': 'Chelsea FC'},
 {'id': 410,
  'primaryhex': '#ffdd00',
  'secondaryhex': '#000000',
  'team': 'Roda JC Kerkrade'},
 {'id': 411,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0379E5',
  'team': 'CD Universidad Católica'},
 {'id': 412,
  'primaryhex': '#0934B3',
  'secondaryhex': '#FAF7F7',
  'team': 'Esteghlal FC'},
 {'id': 413,
  'primaryhex': '#006FFF',
  'secondaryhex': '#FFFFFF',
  'team': 'USL Dunkerque'},
 {'id': 414,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'LASK'},
 {'id': 415,
  'primaryhex': '#025FAC',
  'secondaryhex': '#FDF105',
  'team': 'Eintracht Braunschweig'},
 {'id': 416,
  'primaryhex': '#339933',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Dordrecht'},
 {'id': 417,
  'primaryhex': '#DFE60C',
  'secondaryhex': '#06167D',
  'team': 'Dunarea Calarasi'},
 {'id': 418,
  'primaryhex': '#009ddb',
  'secondaryhex': '#000000',
  'team': 'CD Macará'},
 {'id': 419,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'LDU Quito'},
 {'id': 420,
  'primaryhex': '#592D87',
  'secondaryhex': '#00B7BF',
  'team': 'Pacific FC'},
 {'id': 421,
  'primaryhex': '#121210',
  'secondaryhex': '#000000',
  'team': 'Team Wellington'},
 {'id': 422,
  'primaryhex': '#00701c',
  'secondaryhex': '#032',
  'team': 'Mohun Bagan AC'},
 {'id': 423,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Fortuna Düsseldorf'},
 {'id': 424,
  'primaryhex': '#006633',
  'secondaryhex': '#FFFFFF',
  'team': 'Entag El Harby'},
 {'id': 425,
  'primaryhex': '#000066',
  'secondaryhex': '#FFCC66',
  'team': 'UNAM Pumas'},
 {'id': 426,
  'primaryhex': '#00a6e8',
  'secondaryhex': '#031669',
  'team': 'Djurgardens IF'},
 {'id': 427,
  'primaryhex': '#800000',
  'secondaryhex': '#B99652',
  'team': 'Valour FC'},
 {'id': 428,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Alianza Petrolera'},
 {'id': 429,
  'primaryhex': '#FF6600',
  'secondaryhex': '#33CC00',
  'team': 'Alanyaspor'},
 {'id': 430,
  'primaryhex': '#F08008',
  'secondaryhex': '#2E1C94',
  'team': 'Luton Town'},
 {'id': 431,
  'primaryhex': '#4A18F0',
  'secondaryhex': '#CCC986',
  'team': 'Charlotte Independence'},
 {'id': 432,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FF9933',
  'team': 'V-Varen Nagasaki'},
 {'id': 433,
  'primaryhex': '#F25E2B',
  'secondaryhex': '#000000',
  'team': 'Borneo FC'},
 {'id': 434,
  'primaryhex': '#ABD3FD',
  'secondaryhex': '#18607D',
  'team': 'Persela Lamongan'},
 {'id': 435,
  'primaryhex': '#3C4E99',
  'secondaryhex': '#FFFFFF',
  'team': 'MSV Duisburg'},
 {'id': 436,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFFF',
  'team': 'Slask Wroclaw'},
 {'id': 437,
  'primaryhex': '#ff0000',
  'secondaryhex': '#ff8800',
  'team': 'Jeju United FC'},
 {'id': 438,
  'primaryhex': '#990033',
  'secondaryhex': '#FF9900',
  'team': 'Bradford City'},
 {'id': 439,
  'primaryhex': '#ee2200',
  'secondaryhex': '#023faf',
  'team': 'Becamex Binh Duong FC'},
 {'id': 440,
  'primaryhex': '#ffff00',
  'secondaryhex': '#0000ff',
  'team': 'Asan Mugunghwa FC'},
 {'id': 441,
  'primaryhex': '#EB9500',
  'secondaryhex': '#0028C7',
  'team': 'PKNS FC'},
 {'id': 442,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000063',
  'team': 'SKA Khabarovsk'},
 {'id': 443,
  'primaryhex': '#36B4E5',
  'secondaryhex': '#002857',
  'team': 'HFX Wanderers FC'},
 {'id': 444,
  'primaryhex': '#e0223C',
  'secondaryhex': '#FFFFFF',
  'team': 'RB Leipzig'},
 {'id': 445,
  'primaryhex': '#252161',
  'secondaryhex': '#eb1d23',
  'team': 'Tiburones Rojos de Veracruz'},
 {'id': 446,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Preußen Münster'},
 {'id': 447,
  'primaryhex': '#fa0a0a',
  'secondaryhex': '#fcfcfc',
  'team': 'Highlands Park FC'},
 {'id': 448,
  'primaryhex': '#d9020d',
  'secondaryhex': '#FFFFFF',
  'team': 'CSKA Moscow'},
 {'id': 449,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Bayer 04 Leverkusen'},
 {'id': 450,
  'primaryhex': '#633492',
  'secondaryhex': '#FDE192',
  'team': 'Orlando City SC'},
 {'id': 451,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#00CC33',
  'team': 'Elche CF'},
 {'id': 452,
  'primaryhex': '#0313F7',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Den Bosch'},
 {'id': 453,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Vila Nova Futebol Clube (GO)'},
 {'id': 454,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'Masry Port Said'},
 {'id': 455,
  'primaryhex': '#eeff00',
  'secondaryhex': '#000000',
  'team': 'Ceres-Negros FC'},
 {'id': 456,
  'primaryhex': '#0053A0',
  'secondaryhex': '#FDBE11',
  'team': 'Leicester City'},
 {'id': 457,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'CD Tenerife'},
 {'id': 458,
  'primaryhex': '#AF2626',
  'secondaryhex': '#0A174A',
  'team': 'Chicago Fire'},
 {'id': 459,
  'primaryhex': '#000066',
  'secondaryhex': '#FFFFFF',
  'team': 'Dundee FC'},
 {'id': 460,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Quang Nam FC'},
 {'id': 461,
  'primaryhex': '#2400D9',
  'secondaryhex': '#FFFFFF',
  'team': 'DRB Tadjenanet'},
 {'id': 462,
  'primaryhex': '#660033',
  'secondaryhex': '#0099FF',
  'team': 'West Ham United'},
 {'id': 463,
  'primaryhex': '#003E80',
  'secondaryhex': '#D9031C',
  'team': 'GD Chaves'},
 {'id': 464,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Sevilla FC'},
 {'id': 465,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FF0000',
  'team': 'FCSB'},
 {'id': 466,
  'primaryhex': '#005F27',
  'secondaryhex': '#FFFFFF',
  'team': 'PFK Ludogorets Razgrad'},
 {'id': 467,
  'primaryhex': '#eeff00',
  'secondaryhex': '#1fb800',
  'team': 'JS Kabylie'},
 {'id': 468,
  'primaryhex': '#000000',
  'secondaryhex': '#FF0000',
  'team': 'US Boulogne'},
 {'id': 469,
  'primaryhex': '#FFAE00',
  'secondaryhex': '#FF0000',
  'team': 'Galatasaray SK'},
 {'id': 470,
  'primaryhex': '#0F59FA',
  'secondaryhex': '#FFFF14',
  'team': 'FC Carl Zeiss Jena'},
 {'id': 471,
  'primaryhex': '#000000',
  'secondaryhex': '#ffea00',
  'team': 'Kairat Almaty'},
 {'id': 472,
  'primaryhex': '#f7ff08',
  'secondaryhex': '#e80000',
  'team': 'US Lecce'},
 {'id': 473,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'AS Monaco'},
 {'id': 474,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#FF0000',
  'team': 'Göztepe'},
 {'id': 475,
  'primaryhex': '#1B73D1',
  'secondaryhex': '#FFFFFF',
  'team': 'Hartlepool United'},
 {'id': 476,
  'primaryhex': '#F2DF0C',
  'secondaryhex': '#1A1717',
  'team': 'Kaizer Chiefs'},
 {'id': 477,
  'primaryhex': '#1D1DE0',
  'secondaryhex': '#E6BD17',
  'team': 'Shrewsbury Town'},
 {'id': 478,
  'primaryhex': '#FF0000',
  'secondaryhex': '#030303',
  'team': 'Helmond Sport'},
 {'id': 479,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'ES Sétif'},
 {'id': 480,
  'primaryhex': '#ffe600',
  'secondaryhex': '#000000',
  'team': 'Vitesse Arnhem'},
 {'id': 481,
  'primaryhex': '#33CCCC',
  'secondaryhex': '#FFFFFF',
  'team': 'TSV Hartberg'},
 {'id': 482,
  'primaryhex': '#FAD20A',
  'secondaryhex': '#080808',
  'team': 'Black Leopards FC'},
 {'id': 483,
  'primaryhex': '#FF6600',
  'secondaryhex': '#000000',
  'team': 'Shakhtar Donetsk'},
 {'id': 484,
  'primaryhex': '#0C18C9',
  'secondaryhex': '#DEA335',
  'team': 'AC Sparta Praha'},
 {'id': 485,
  'primaryhex': '#54555A',
  'secondaryhex': '#BF4517',
  'team': 'Forge FC'},
 {'id': 486,
  'primaryhex': '#E2001A',
  'secondaryhex': '#FFFEFF',
  'team': 'FC Thun'},
 {'id': 487,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'El Dakhlia SC'},
 {'id': 488,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Club Atlético Huracán'},
 {'id': 489,
  'primaryhex': '#990000',
  'secondaryhex': '#FFFFFF',
  'team': '1.FC Nuremberg'},
 {'id': 490,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Royal Antwerp FC'},
 {'id': 491,
  'primaryhex': '#66CCFF',
  'secondaryhex': '#000000',
  'team': 'Kawasaki Frontale'},
 {'id': 492,
  'primaryhex': '#0000FF',
  'secondaryhex': '#000000',
  'team': 'Club Brugge KV'},
 {'id': 493,
  'primaryhex': '#0C944C',
  'secondaryhex': '#F2F229',
  'team': 'Bhayangkara FC'},
 {'id': 494,
  'primaryhex': '#0070B5',
  'secondaryhex': '#D11524',
  'team': 'Cardiff City'},
 {'id': 495,
  'primaryhex': '#EBA10C',
  'secondaryhex': '#000000',
  'team': 'Newport County'},
 {'id': 496,
  'primaryhex': '#050505',
  'secondaryhex': '#FFFFFF',
  'team': 'Clube Atlético Mineiro'},
 {'id': 497,
  'primaryhex': '#000000',
  'secondaryhex': '#DD0000',
  'team': 'D.C. United'},
 {'id': 498,
  'primaryhex': '#ff0000',
  'secondaryhex': '#fafafa',
  'team': 'FK Vojvodina Novi Sad'},
 {'id': 499,
  'primaryhex': '#f7ea36',
  'secondaryhex': '#000000',
  'team': 'NAC Breda'},
 {'id': 500,
  'primaryhex': '#FFFB00',
  'secondaryhex': '#003CFF',
  'team': 'Kerala Blasters FC'},
 {'id': 501,
  'primaryhex': '#F50E0E',
  'secondaryhex': '#FFFFFF',
  'team': 'Free State Stars'},
 {'id': 502,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'SK Sturm Graz'},
 {'id': 503,
  'primaryhex': '#E80000',
  'secondaryhex': '#FFFFFF',
  'team': 'SC Fortuna Köln'},
 {'id': 504,
  'primaryhex': '#08992F',
  'secondaryhex': '#FFFFFF',
  'team': 'Al-Ahli Jeddah'},
 {'id': 505,
  'primaryhex': '#ff0000',
  'secondaryhex': '#214180',
  'team': 'Chongqing Dangdai Lifan'},
 {'id': 506,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000066',
  'team': 'Kagoshima United'},
 {'id': 507,
  'primaryhex': '#FAFA05',
  'secondaryhex': '#70E610',
  'team': 'Mamelodi Sundowns FC'},
 {'id': 508,
  'primaryhex': '#0cc6f5',
  'secondaryhex': '#141b9e',
  'team': 'FK Rad'},
 {'id': 509,
  'primaryhex': '#0033CC',
  'secondaryhex': '#FFFFFF',
  'team': 'Karlsruher SC'},
 {'id': 510,
  'primaryhex': '#141FAA',
  'secondaryhex': '#FFFFFF',
  'team': 'CD Cruz Azul'},
 {'id': 511,
  'primaryhex': '#FF3300',
  'secondaryhex': '#DBFF4A',
  'team': 'NA Hussein Dey'},
 {'id': 512,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFF00',
  'team': 'Montedio Yamagata'},
 {'id': 513,
  'primaryhex': '#CC1010',
  'secondaryhex': '#080808',
  'team': 'Esporte Clube Vitória'},
 {'id': 514,
  'primaryhex': '#000000',
  'secondaryhex': '#FF0000',
  'team': 'FC Ingolstadt 04'},
 {'id': 515,
  'primaryhex': '#0022FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Wisla Kraków'},
 {'id': 516,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'RCD Mallorca'},
 {'id': 517,
  'primaryhex': '#FF0000',
  'secondaryhex': '#EEFF00',
  'team': 'Selangor FA'},
 {'id': 518,
  'primaryhex': '#0000CC',
  'secondaryhex': '#FF0000',
  'team': 'FC Tokyo'},
 {'id': 519,
  'primaryhex': '#511972',
  'secondaryhex': '#FFFFFF',
  'team': 'VfL Osnabrück'},
 {'id': 520,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'Al Sadd Sports Club'},
 {'id': 521,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFF00',
  'team': 'Esperance Tunis'},
 {'id': 522,
  'primaryhex': '#5E9E4B',
  'secondaryhex': '#EE3224',
  'team': 'Stade Tunisien'},
 {'id': 523,
  'primaryhex': '#000066',
  'secondaryhex': '#FFFFFF',
  'team': 'Auckland City FC'},
 {'id': 524,
  'primaryhex': '#fffb00',
  'secondaryhex': '#003cf0',
  'team': 'Al-Nassr FC'},
 {'id': 525,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'AZ Alkmaar'},
 {'id': 526,
  'primaryhex': '#FF0033',
  'secondaryhex': '#ffffff',
  'team': 'Shenzhen FC'},
 {'id': 527,
  'primaryhex': '#FF0500',
  'secondaryhex': '#FFFFFF',
  'team': 'Atlético Madrid'},
 {'id': 528,
  'primaryhex': '#004F3E',
  'secondaryhex': '#FFFFFF',
  'team': 'Plymouth Argyle'},
 {'id': 529,
  'primaryhex': '#ff0000',
  'secondaryhex': '#000000',
  'team': 'FC Seoul'},
 {'id': 530,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#007818',
  'team': 'CD Palestino'},
 {'id': 531,
  'primaryhex': '#FF9900',
  'secondaryhex': '#000000',
  'team': 'Barnet FC'},
 {'id': 532,
  'primaryhex': '#00871b',
  'secondaryhex': '#eff700',
  'team': 'Tobol Kostanay'},
 {'id': 533,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'SV Sandhausen'},
 {'id': 534,
  'primaryhex': '#660000',
  'secondaryhex': '#FFFFFF',
  'team': 'Heart of Midlothian FC'},
 {'id': 535,
  'primaryhex': '#F0D313',
  'secondaryhex': '#0F0303',
  'team': 'Cambridge United'},
 {'id': 536,
  'primaryhex': '#660033',
  'secondaryhex': '#6699FF',
  'team': 'Aston Villa'},
 {'id': 537,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FAFAFA',
  'team': 'FC Hermannstadt'},
 {'id': 538,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Salford City'},
 {'id': 539,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0000FF',
  'team': 'Club Nacional'},
 {'id': 540,
  'primaryhex': '#006633',
  'secondaryhex': '#FFFFFF',
  'team': 'Akhisarspor'},
 {'id': 541,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'St. Johnstone FC'},
 {'id': 542,
  'primaryhex': '#bb3532',
  'secondaryhex': '#006633',
  'team': 'FC Augsburg'},
 {'id': 543,
  'primaryhex': '#00E3EB',
  'secondaryhex': '#FFFCFC',
  'team': 'Club Atlético Cerro'},
 {'id': 544,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0000FF',
  'team': 'Dynamo Kyiv'},
 {'id': 545,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'SC Freiburg'},
 {'id': 546,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Exeter City'},
 {'id': 547,
  'primaryhex': '#0703ff',
  'secondaryhex': '#f59803',
  'team': 'Orange County SC'},
 {'id': 548,
  'primaryhex': '#7811D9',
  'secondaryhex': '#EBE123',
  'team': 'Louisville City FC'},
 {'id': 549,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'KSC Lokeren'},
 {'id': 550,
  'primaryhex': '#003300',
  'secondaryhex': '#003399',
  'team': 'Masr El Makasa'},
 {'id': 551,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#FF0000',
  'team': 'CS Herediano'},
 {'id': 552,
  'primaryhex': '#ED0E0E',
  'secondaryhex': '#EAFF00',
  'team': 'Gokulam Kerala FC'},
 {'id': 553,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Canterbury United'},
 {'id': 554,
  'primaryhex': '#2D2DD4',
  'secondaryhex': '#FFFFFF',
  'team': 'PEC Zwolle'},
 {'id': 555,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'FAR Rabat'},
 {'id': 556,
  'primaryhex': '#610087',
  'secondaryhex': '#fcf9f9',
  'team': 'Defensor Sporting Club'},
 {'id': 557,
  'primaryhex': '#139100',
  'secondaryhex': '#FFFFFF',
  'team': 'Audax Italiano'},
 {'id': 558,
  'primaryhex': '#ff0000',
  'secondaryhex': '#e1ff00',
  'team': 'Foolad FC'},
 {'id': 559,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000CC',
  'team': 'Tigres UANL'},
 {'id': 560,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Ajax Amsterdam'},
 {'id': 561,
  'primaryhex': '#fff71c',
  'secondaryhex': '#e3002d',
  'team': 'Watford FC'},
 {'id': 562,
  'primaryhex': '#F0F027',
  'secondaryhex': '#3910E0',
  'team': 'Chievo Verona'},
 {'id': 563,
  'primaryhex': '#fafafa',
  'secondaryhex': '#141313',
  'team': 'Spezia Calcio'},
 {'id': 564,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'El Ahly Cairo'},
 {'id': 565,
  'primaryhex': '#151073',
  'secondaryhex': '#E0A70B',
  'team': 'Los Angeles Galaxy II'},
 {'id': 566,
  'primaryhex': '#DD0000',
  'secondaryhex': '#FFD700',
  'team': 'Hai Phong FC'},
 {'id': 567,
  'primaryhex': '#0047ab',
  'secondaryhex': '#c4adac',
  'team': 'Reno 1868 FC'},
 {'id': 568,
  'primaryhex': '#0033CC',
  'secondaryhex': '#CC0000',
  'team': 'Miedz Legnica'},
 {'id': 569,
  'primaryhex': '#0A2141',
  'secondaryhex': '#D80016',
  'team': 'New England Revolution'},
 {'id': 570,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Bristol Rovers'},
 {'id': 571,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFFF',
  'team': 'Cercle Brugge '},
 {'id': 572,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Athletic Bilbao'},
 {'id': 573,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Arsenal Kyiv'},
 {'id': 574,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'KAS Eupen'},
 {'id': 575,
  'primaryhex': '#FF0000',
  'secondaryhex': '#EEFF00',
  'team': 'Unión Española'},
 {'id': 576,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Harras El Hodoud'},
 {'id': 577,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Ajax Amsterdam U21'},
 {'id': 578,
  'primaryhex': '#136B0E',
  'secondaryhex': '#FFFFFF',
  'team': 'Melaka United SA'},
 {'id': 579,
  'primaryhex': '#3050d1',
  'secondaryhex': '#ffffff',
  'team': 'Esteghlal Khuzestan'},
 {'id': 580,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Eintracht Frankfurt'},
 {'id': 581,
  'primaryhex': '#ff0808',
  'secondaryhex': '#FFFFFF',
  'team': 'Feyenoord Rotterdam'},
 {'id': 582,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#C0C0C0',
  'team': 'SD Aucas'},
 {'id': 583,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'KV Kortrijk'},
 {'id': 584,
  'primaryhex': '#009900',
  'secondaryhex': '#FF0000',
  'team': 'KV Oostende'},
 {'id': 585,
  'primaryhex': '#33CC00',
  'secondaryhex': '#FFFFFF',
  'team': 'Difaâ El Jadida'},
 {'id': 586,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Waasland-Beveren'},
 {'id': 587,
  'primaryhex': '#ff7700',
  'secondaryhex': '#000000',
  'team': 'Shakhter Karaganda'},
 {'id': 588,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Kilmarnock FC'},
 {'id': 589,
  'primaryhex': '#fc0505',
  'secondaryhex': '#0303fa',
  'team': 'Panionios Athens'},
 {'id': 590,
  'primaryhex': '#F70505',
  'secondaryhex': '#FFFFFF',
  'team': 'Persepolis FC'},
 {'id': 591,
  'primaryhex': '#008000',
  'secondaryhex': '#FFFFFF',
  'team': 'Concordia Chiajna'},
 {'id': 592,
  'primaryhex': '#1D3DC8',
  'secondaryhex': '#F6D000',
  'team': 'SKN St. Pölten'},
 {'id': 593,
  'primaryhex': '#099902',
  'secondaryhex': '#000000',
  'team': 'US Sassuolo'},
 {'id': 594,
  'primaryhex': '#9dc3e8',
  'secondaryhex': '#1f0f4a',
  'team': 'Guayaquil City FC'},
 {'id': 595,
  'primaryhex': '#ede100',
  'secondaryhex': '#000000',
  'team': 'Al-Ittihad Jeddah'},
 {'id': 596,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FF0000',
  'team': 'Yokohama F. Marinos'},
 {'id': 597,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Zorya Luhansk'},
 {'id': 598,
  'primaryhex': '#014495',
  'secondaryhex': '#FFFFFF',
  'team': 'Hamburger SV'},
 {'id': 599,
  'primaryhex': '#3300FF',
  'secondaryhex': '#FFFFFF',
  'team': '1.FC Magdeburg'},
 {'id': 600,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Reading FC'},
 {'id': 601,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'FK Armavir'},
 {'id': 602,
  'primaryhex': '#F50C0C',
  'secondaryhex': '#FFFFFF',
  'team': 'Red Star Belgrade'},
 {'id': 603,
  'primaryhex': '#000000',
  'secondaryhex': '#FFDB00',
  'team': 'Columbus Crew SC'},
 {'id': 604,
  'primaryhex': '#14468B',
  'secondaryhex': '#DD0036',
  'team': 'Club Atlético Tigre'},
 {'id': 605,
  'primaryhex': '#800000',
  'secondaryhex': '#000080',
  'team': 'Extremadura UD'},
 {'id': 606,
  'primaryhex': '#FA0505',
  'secondaryhex': '#080808',
  'team': "Club Atlético Newell's Old Boys"},
 {'id': 607,
  'primaryhex': '#6aacdf',
  'secondaryhex': '#00285E',
  'team': 'New York City FC'},
 {'id': 608,
  'primaryhex': '#fac000',
  'secondaryhex': '#00732c',
  'team': 'Venados FC Yucatán'},
 {'id': 609,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Newcastle United'},
 {'id': 610,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Wydad Casablanca'},
 {'id': 611,
  'primaryhex': '#FCE808',
  'secondaryhex': '#FF0000',
  'team': 'Club Atlético Progreso'},
 {'id': 612,
  'primaryhex': '#11B846',
  'secondaryhex': '#FFFFFF',
  'team': 'AmaZulu FC'},
 {'id': 613,
  'primaryhex': '#76BC21',
  'secondaryhex': '#363A36',
  'team': 'York9 FC'},
 {'id': 614,
  'primaryhex': '#D80016',
  'secondaryhex': '#313F49',
  'team': 'Toronto FC'},
 {'id': 615,
  'primaryhex': '#0066FF',
  'secondaryhex': '#FFFFFF',
  'team': 'De Graafschap Doetinchem'},
 {'id': 616,
  'primaryhex': '#EBE121',
  'secondaryhex': '#1A4FD4',
  'team': 'Sanat Naft FC'},
 {'id': 617,
  'primaryhex': '#7A003C',
  'secondaryhex': '#FFFFFF',
  'team': 'Deportivo Saprissa'},
 {'id': 618,
  'primaryhex': '#ab0a0a',
  'secondaryhex': '#0f0f6b',
  'team': 'Cagliari Calcio'},
 {'id': 619,
  'primaryhex': '#2bcc84',
  'secondaryhex': '#3447d9',
  'team': 'Oklahoma City Energy FC'},
 {'id': 620,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': "Tala'ea El Gaish"},
 {'id': 621,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#009933',
  'team': 'SpVgg Greuther Fürth'},
 {'id': 622,
  'primaryhex': '#00961e',
  'secondaryhex': '#f7faf7',
  'team': 'Club Plaza Colonia'},
 {'id': 623,
  'primaryhex': '#0b06b3',
  'secondaryhex': '#fafafa',
  'team': 'Delfino Pescara 1936'},
 {'id': 624,
  'primaryhex': '#FEF100',
  'secondaryhex': '#ED1B24',
  'team': 'Etoile Sportive Metlaoui'},
 {'id': 625,
  'primaryhex': '#000000',
  'secondaryhex': '#FFD800',
  'team': 'Union Sportive de Ben Guerdane'},
 {'id': 626,
  'primaryhex': '#ff0000',
  'secondaryhex': '#ffffff',
  'team': 'Guangzhou Evergrande Taobao'},
 {'id': 627,
  'primaryhex': '#ff0808',
  'secondaryhex': '#098518',
  'team': 'Lokomotiv Tashkent'},
 {'id': 628,
  'primaryhex': '#ED1C23',
  'secondaryhex': '#FFFFFF',
  'team': 'PSV Eindhoven U21'},
 {'id': 629,
  'primaryhex': '#705e07',
  'secondaryhex': '#f0e628',
  'team': 'Ohod Al-Medina'},
 {'id': 630,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Spartak Moscow'},
 {'id': 631,
  'primaryhex': '#00cc00',
  'secondaryhex': '#fffb00',
  'team': 'Ansan Greeners FC'},
 {'id': 632,
  'primaryhex': '#A4BBD7',
  'secondaryhex': '#0A2141',
  'team': 'Sporting Kansas City'},
 {'id': 633,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#099FFF',
  'team': 'Olympique Marseille'},
 {'id': 634,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFff',
  'team': 'Anzhi Makhachkala'},
 {'id': 635,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Besiktas JK'},
 {'id': 636,
  'primaryhex': '#E00000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Vaduz'},
 {'id': 637,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#001C58',
  'team': 'Tottenham Hotspur'},
 {'id': 638,
  'primaryhex': '#ffb22e',
  'secondaryhex': '#9e142b',
  'team': 'AS Roma'},
 {'id': 639,
  'primaryhex': '#08007a',
  'secondaryhex': '#ff0000',
  'team': 'Club Universidad de Chile'},
 {'id': 640,
  'primaryhex': '#009900',
  'secondaryhex': '#FFFF00',
  'team': 'Norwich City'},
 {'id': 641,
  'primaryhex': '#BF0C10',
  'secondaryhex': '#0C0D0F',
  'team': 'AFC Bournemouth'},
 {'id': 642,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF6220',
  'team': 'Mushuc Runa SC'},
 {'id': 643,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'São Paulo Futebol Clube'},
 {'id': 644,
  'primaryhex': '#0037eb',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Porto B'},
 {'id': 645,
  'primaryhex': '#ffea00',
  'secondaryhex': '#000000',
  'team': 'Wellington Phoenix Reserves'},
 {'id': 646,
  'primaryhex': '#000000',
  'secondaryhex': '#B31010',
  'team': 'Ottawa Fury FC'},
 {'id': 647,
  'primaryhex': '#FFFF66',
  'secondaryhex': '#0033FF',
  'team': 'Ismaily SC'},
 {'id': 648,
  'primaryhex': '#FF0033',
  'secondaryhex': '#FFFFFF',
  'team': 'MVV Maastricht'},
 {'id': 649,
  'primaryhex': '#006633',
  'secondaryhex': '#FFFFFF',
  'team': 'Hibernian FC'},
 {'id': 650,
  'primaryhex': '#123163',
  'secondaryhex': '#FFFF00',
  'team': 'Central Coast Mariners'},
 {'id': 651,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'Celtic FC'},
 {'id': 652,
  'primaryhex': '#BA2C22',
  'secondaryhex': '#FFFFFF',
  'team': 'Shanghai SIPG'},
 {'id': 653,
  'primaryhex': '#0d6ecd',
  'secondaryhex': '#FFFFFF',
  'team': 'Dinamo Moscow'},
 {'id': 654,
  'primaryhex': '#0000CC',
  'secondaryhex': '#FFFFFF',
  'team': 'Wisla Plock'}]
 export default TeamData