const TeamData = [

{"id": "1", "team": "Arsenal", "primaryhex": "#DC0001", "secondaryhex": "#003175"},
{"id": "2", "team": "Bournemouth", "primaryhex": "#E70404", "secondaryhex": "#000000"},
{"id": "3", "team": "Brighton", "primaryhex": "#005DAA", "secondaryhex": "#FFFFFF"},
{"id": "4", "team": "Burnley", "primaryhex": "#630630", "secondaryhex": "#98DAF5"},
{"id": "5", "team": "Cardiff", "primaryhex": "#2757AF", "secondaryhex": "#FFFFFF"},
{"id": "6", "team": "Chelsea", "primaryhex": "#034694", "secondaryhex": "#ED2129"},
{"id": "7", "team": "Crystal Palace", "primaryhex": "#144390", "secondaryhex": "#C50A2A"},
{"id": "8", "team": "Everton", "primaryhex": "#224289", "secondaryhex": "#FFFFFF"},
{"id": "9", "team": "Fulham", "primaryhex": "#FFFFFF", "secondaryhex": "#000000"},
{"id": "10", "team": "Huddersfield Town", "primaryhex": "#0073CF", "secondaryhex": "#FFFFFF"},
{"id": "11", "team": "Leicester City", "primaryhex": "#0052A1", "secondaryhex": "#FFFFFF"},
{"id": "12", "team": "Liverpool", "primaryhex": "#DC0100", "secondaryhex": "#FFFFFF"},
{"id": "13", "team": "Man City", "primaryhex": "#B7D9F5", "secondaryhex": "#1C204E"},
{"id": "14", "team": "Man Utd", "primaryhex": "#E70404", "secondaryhex": "#000000"},
{"id": "15", "team": "Newcastle Utd", "primaryhex": "#000000", "secondaryhex": "#FFFFFF"},
{"id": "16", "team": "Southampton", "primaryhex": "#FF0000", "secondaryhex": "#FFFFFF"},
{"id": "17", "team": "Spurs", "primaryhex": "#FFFFFF", "secondaryhex": "#0B1C56"},
{"id": "18", "team": "Watford", "primaryhex": "#FBEE1E", "secondaryhex": "#000000"},
{"id": "19", "team": "West Ham", "primaryhex": "#810133", "secondaryhex": "#69AEC4"},
{"id": "20", "team": "Wolves", "primaryhex": "#000000", "secondaryhex": "#FDBA0B"},
{"id": "35", "team": "Accrington Stanley", "primaryhex": "#DC0100", "secondaryhex": "#FFFFFF"},

][{'id': 1,
  'primaryhex': '#0080FF',
  'secondaryhex': '#ffffff',
  'team': 'SSC Napoli'},
 {'id': 2,
  'primaryhex': '#172f6b',
  'secondaryhex': '#ffffff',
  'team': 'Belenenses SAD'},
 {'id': 3,
  'primaryhex': '#000000',
  'secondaryhex': '#0055A0',
  'team': 'Inter Milan'},
 {'id': 4,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Desna Chernihiv'},
 {'id': 5,
  'primaryhex': '#ffe600',
  'secondaryhex': '#000000',
  'team': 'Vitesse Arnhem'},
 {'id': 6,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'AIK'},
 {'id': 7,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': '1.FSV Mainz 05'},
 {'id': 8,
  'primaryhex': '#ffffff',
  'secondaryhex': '#000000',
  'team': 'Slavia Sofia'},
 {'id': 9,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Panetolikos GFS'},
 {'id': 10,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Politehnica Iasi'},
 {'id': 11,
  'primaryhex': '#0d19ba',
  'secondaryhex': '#0d19ba',
  'team': 'FK Orenburg'},
 {'id': 12,
  'primaryhex': '#3456a1',
  'secondaryhex': '#78b3e3',
  'team': 'NK Osijek'},
 {'id': 13,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Esbjerg fB'},
 {'id': 14,
  'primaryhex': '#33CCCC',
  'secondaryhex': '#FFFFFF',
  'team': 'TSV Hartberg'},
 {'id': 15,
  'primaryhex': '#e01212',
  'secondaryhex': '#0707e0',
  'team': 'SD Eibar'},
 {'id': 16,
  'primaryhex': '#008056',
  'secondaryhex': '#FFFFFF',
  'team': 'Sporting CP'},
 {'id': 17,
  'primaryhex': '#FF6600',
  'secondaryhex': '#000000',
  'team': 'Shakhtar Donetsk'},
 {'id': 18,
  'primaryhex': '#FF0000',
  'secondaryhex': '#009900',
  'team': 'SV Zulte Waregem'},
 {'id': 19,
  'primaryhex': '#0D258F',
  'secondaryhex': '#000000',
  'team': '1.FC Slovácko'},
 {'id': 20,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'HNK Rijeka'},
 {'id': 21,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'CD Nacional'},
 {'id': 22,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Banik Ostrava'},
 {'id': 23,
  'primaryhex': '#0C18C9',
  'secondaryhex': '#DEA335',
  'team': 'AC Sparta Praha'},
 {'id': 24,
  'primaryhex': '#FF6600',
  'secondaryhex': '#000000',
  'team': 'Ural Yekaterinburg'},
 {'id': 25,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Nordsjaelland'},
 {'id': 26,
  'primaryhex': '#3d84ff',
  'secondaryhex': '#ffffff',
  'team': 'Krylya Sovetov Samara'},
 {'id': 27,
  'primaryhex': '#33CCFF',
  'secondaryhex': '#FFFFFF',
  'team': 'Manchester City'},
 {'id': 28,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Helsingborgs IF'},
 {'id': 29,
  'primaryhex': '#E2001A',
  'secondaryhex': '#FFFEFF',
  'team': 'FC Thun'},
 {'id': 30,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Fulham FC'},
 {'id': 31,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'Bursaspor'},
 {'id': 32,
  'primaryhex': '#990000',
  'secondaryhex': '#FFFFFF',
  'team': '1.FC Nuremberg'},
 {'id': 33,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Dunav Ruse'},
 {'id': 34,
  'primaryhex': '#ffea00',
  'secondaryhex': '#000000',
  'team': 'VVV-Venlo'},
 {'id': 35,
  'primaryhex': '#0037eb',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Porto'},
 {'id': 36,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Royal Antwerp FC'},
 {'id': 37,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'HNK Gorica'},
 {'id': 38,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Mladá Boleslav'},
 {'id': 39,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'Astra Giurgiu'},
 {'id': 40,
  'primaryhex': '#0000FF',
  'secondaryhex': '#000000',
  'team': 'Club Brugge KV'},
 {'id': 41,
  'primaryhex': '#d62424',
  'secondaryhex': '#000000',
  'team': 'FK Macva Sabac'},
 {'id': 42,
  'primaryhex': '#FF9900',
  'secondaryhex': '#FFFFFF',
  'team': 'Istanbul Basaksehir FK'},
 {'id': 43,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Olympiacos Piraeus'},
 {'id': 44,
  'primaryhex': '#ff0000',
  'secondaryhex': '#f7ff00',
  'team': 'Arsenal Tula'},
 {'id': 45,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Livingston FC'},
 {'id': 46,
  'primaryhex': '#089908',
  'secondaryhex': '#fcf803',
  'team': 'Fortuna Sittard'},
 {'id': 47,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Dinamo Bukarest'},
 {'id': 48,
  'primaryhex': '#1c388c',
  'secondaryhex': '#E32118',
  'team': 'GNK Dinamo Zagreb'},
 {'id': 49,
  'primaryhex': '#0070B5',
  'secondaryhex': '#D11524',
  'team': 'Cardiff City'},
 {'id': 50,
  'primaryhex': '#000979',
  'secondaryhex': '#FF0000',
  'team': 'Paris Saint-Germain'},
 {'id': 51,
  'primaryhex': '#FF0000',
  'secondaryhex': '#ffffff',
  'team': 'Lokomotiv Moscow'},
 {'id': 52,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Real Valladolid CF'},
 {'id': 53,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Oleksandria'},
 {'id': 54,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'RSC Charleroi'},
 {'id': 55,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Copenhagen'},
 {'id': 56,
  'primaryhex': '#81C0FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Malmö FF'},
 {'id': 57,
  'primaryhex': '#ffffff',
  'secondaryhex': '#001cd4',
  'team': 'Irtysh Pavlodar'},
 {'id': 58,
  'primaryhex': '#ff0000',
  'secondaryhex': '#fafafa',
  'team': 'FK Vojvodina Novi Sad'},
 {'id': 59,
  'primaryhex': '#000000',
  'secondaryhex': '#158c43',
  'team': 'FK Krasnodar'},
 {'id': 60,
  'primaryhex': '#66CC00',
  'secondaryhex': '#FFFFFF',
  'team': 'VfL Wolfsburg'},
 {'id': 61,
  'primaryhex': '#f7ea36',
  'secondaryhex': '#000000',
  'team': 'NAC Breda'},
 {'id': 62,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Standard Liège'},
 {'id': 63,
  'primaryhex': '#ed1c24',
  'secondaryhex': '#ffffff',
  'team': 'Enisey Krasnoyarsk'},
 {'id': 64,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'SK Sturm Graz'},
 {'id': 65,
  'primaryhex': '#0000FF',
  'secondaryhex': '#0000FF',
  'team': 'Getafe CF'},
 {'id': 66,
  'primaryhex': '#ffffff',
  'secondaryhex': '#000000',
  'team': 'Vitória Guimarães SC'},
 {'id': 67,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Moreirense FC'},
 {'id': 68,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'SönderjyskE'},
 {'id': 69,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'BK Häcken'},
 {'id': 70,
  'primaryhex': '#0cc6f5',
  'secondaryhex': '#141b9e',
  'team': 'FK Rad'},
 {'id': 71,
  'primaryhex': '#fa2d2d',
  'secondaryhex': '#030303',
  'team': 'FK Napredak Krusevac'},
 {'id': 72,
  'primaryhex': '#ed0909',
  'secondaryhex': '#483deb',
  'team': 'Bologna FC 1909'},
 {'id': 73,
  'primaryhex': '#175eeb',
  'secondaryhex': '#ffffff',
  'team': 'FC Empoli'},
 {'id': 74,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'SV Werder Bremen'},
 {'id': 75,
  'primaryhex': '#0052cc',
  'secondaryhex': '#FFFFFF',
  'team': 'Everton FC'},
 {'id': 76,
  'primaryhex': '#a62d2d',
  'secondaryhex': '#ffffff',
  'team': 'Torino FC'},
 {'id': 77,
  'primaryhex': '#fffb00',
  'secondaryhex': '#0091ff',
  'team': 'Bröndby IF'},
 {'id': 78,
  'primaryhex': '#99CCFF',
  'secondaryhex': '#FFFFFF',
  'team': 'Celta de Vigo'},
 {'id': 79,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Mariupol'},
 {'id': 80,
  'primaryhex': '#009900',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Groningen'},
 {'id': 81,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Falkenbergs FF'},
 {'id': 82,
  'primaryhex': '#b50909',
  'secondaryhex': '#050505',
  'team': 'AC Milan'},
 {'id': 83,
  'primaryhex': '#0022FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Wisla Kraków'},
 {'id': 84,
  'primaryhex': '#008141',
  'secondaryhex': '#FFFFFF',
  'team': 'FC St. Gallen 1879'},
 {'id': 85,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Slaven Belupo Koprivnica'},
 {'id': 86,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Voluntari'},
 {'id': 87,
  'primaryhex': '#000000',
  'secondaryhex': '#ffffff',
  'team': 'Udinese Calcio'},
 {'id': 88,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Okzhetpes Kokshetau'},
 {'id': 89,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'IK Sirius'},
 {'id': 90,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Dukla Prag'},
 {'id': 91,
  'primaryhex': '#1B458F',
  'secondaryhex': '#C4122E',
  'team': 'Crystal Palace'},
 {'id': 92,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0000FF',
  'team': 'KRC Genk'},
 {'id': 93,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'HNK Hajduk Split'},
 {'id': 94,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#660099',
  'team': 'RSC Anderlecht'},
 {'id': 95,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'AZ Alkmaar'},
 {'id': 96,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0073ff',
  'team': 'Villarreal CF'},
 {'id': 97,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Boavista Porto FC'},
 {'id': 98,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Konyaspor'},
 {'id': 99,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'RC Strasbourg Alsace'},
 {'id': 100,
  'primaryhex': '#FF0500',
  'secondaryhex': '#FFFFFF',
  'team': 'Atlético Madrid'},
 {'id': 101,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Vitória Setúbal FC'},
 {'id': 102,
  'primaryhex': '#ffff00',
  'secondaryhex': '#000000',
  'team': 'AEK Athens'},
 {'id': 103,
  'primaryhex': '#00238a',
  'secondaryhex': '#ffffff',
  'team': 'Ordabasy Shymkent'},
 {'id': 104,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'SC Amiens'},
 {'id': 105,
  'primaryhex': '#00871b',
  'secondaryhex': '#eff700',
  'team': 'Tobol Kostanay'},
 {'id': 106,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'SC Rheindorf Altach'},
 {'id': 107,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'PAS Lamia 1964'},
 {'id': 108,
  'primaryhex': '#660000',
  'secondaryhex': '#FFFFFF',
  'team': 'Heart of Midlothian FC'},
 {'id': 109,
  'primaryhex': '#E0E01B',
  'secondaryhex': '#1D03AD',
  'team': 'FK Dinamo Vranje'},
 {'id': 110,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFF00',
  'team': 'ADO Den Haag'},
 {'id': 111,
  'primaryhex': '#0004fa',
  'secondaryhex': '#ffffff',
  'team': 'SK Sigma Olomouc'},
 {'id': 112,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FAFAFA',
  'team': 'FC Hermannstadt'},
 {'id': 113,
  'primaryhex': '#cc0000',
  'secondaryhex': '#ffffff',
  'team': 'Liverpool FC'},
 {'id': 114,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Valencia CF'},
 {'id': 115,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Sint-Truidense VV'},
 {'id': 116,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Kayserispor'},
 {'id': 117,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'SD Huesca'},
 {'id': 118,
  'primaryhex': '#00b30c',
  'secondaryhex': '#ffffff',
  'team': 'Cherno More Varna'},
 {'id': 119,
  'primaryhex': '#006633',
  'secondaryhex': '#FFFFFF',
  'team': 'Akhisarspor'},
 {'id': 120,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FCO Dijon'},
 {'id': 121,
  'primaryhex': '#ff0000',
  'secondaryhex': '#ffffff',
  'team': 'Legia Warszawa'},
 {'id': 122,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'AO Xanthi'},
 {'id': 123,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'St. Johnstone FC'},
 {'id': 124,
  'primaryhex': '#1f8c2b',
  'secondaryhex': '#ffffff',
  'team': 'FK Zemun'},
 {'id': 125,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Deportivo Alavés'},
 {'id': 126,
  'primaryhex': '#bb3532',
  'secondaryhex': '#006633',
  'team': 'FC Augsburg'},
 {'id': 127,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'AS Saint-Étienne'},
 {'id': 128,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Etar Veliko Tarnovo'},
 {'id': 129,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'SM Caen'},
 {'id': 130,
  'primaryhex': '#b80707',
  'secondaryhex': '#ffffff',
  'team': 'SK Slavia Prag'},
 {'id': 131,
  'primaryhex': '#f02828',
  'secondaryhex': '#ffffff',
  'team': 'FK Proleter Novi Sad'},
 {'id': 132,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0000FF',
  'team': 'Dynamo Kyiv'},
 {'id': 133,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Yeni Malatyaspor'},
 {'id': 134,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'SC Freiburg'},
 {'id': 135,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Odense Boldklub'},
 {'id': 136,
  'primaryhex': '#8a0707',
  'secondaryhex': '#000000',
  'team': 'Lokomotiv Plovdiv'},
 {'id': 137,
  'primaryhex': '#25b4f7',
  'secondaryhex': '#ffffff',
  'team': 'OFK Backa'},
 {'id': 138,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#000000',
  'team': 'KSC Lokeren'},
 {'id': 139,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Zenit St. Petersburg'},
 {'id': 140,
  'primaryhex': '#ff0000',
  'secondaryhex': '#0000ff',
  'team': 'Olympique Lyon'},
 {'id': 141,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Vitosha Bistritsa'},
 {'id': 142,
  'primaryhex': '#ffffff',
  'secondaryhex': '#000000',
  'team': 'Portimonense SC'},
 {'id': 143,
  'primaryhex': '#3c9135',
  'secondaryhex': '#3c9135',
  'team': 'Akhmat Grozny'},
 {'id': 144,
  'primaryhex': '#F20505',
  'secondaryhex': '#FFFFFF',
  'team': 'LOSC Lille'},
 {'id': 145,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0033CC',
  'team': 'KAA Gent'},
 {'id': 146,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Aarhus GF'},
 {'id': 147,
  'primaryhex': '#2D2DD4',
  'secondaryhex': '#FFFFFF',
  'team': 'PEC Zwolle'},
 {'id': 148,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Septemvri Sofia'},
 {'id': 149,
  'primaryhex': '#614c99',
  'secondaryhex': '#614c99',
  'team': 'ACF Fiorentina'},
 {'id': 150,
  'primaryhex': '#018202',
  'secondaryhex': '#FFFFFF',
  'team': 'SV Mattersburg'},
 {'id': 151,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Taraz'},
 {'id': 152,
  'primaryhex': '#187A2F',
  'secondaryhex': '#042FBF',
  'team': 'Caykur Rizespor'},
 {'id': 153,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000000',
  'team': 'Botev Plovdiv'},
 {'id': 154,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'CD Leganés'},
 {'id': 155,
  'primaryhex': '#515ee8',
  'secondaryhex': '#f5ebeb',
  'team': 'UC Sampdoria'},
 {'id': 156,
  'primaryhex': '#441678',
  'secondaryhex': '#FFFFFF',
  'team': 'Austria Vienna'},
 {'id': 157,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#0A67B7',
  'team': 'CS Universitatea Craiova'},
 {'id': 158,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Ajax Amsterdam'},
 {'id': 159,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Hobro IK'},
 {'id': 160,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Aalborg BK'},
 {'id': 161,
  'primaryhex': '#ff0000',
  'secondaryhex': '#168500',
  'team': 'Zaglebie Sosnowiec'},
 {'id': 162,
  'primaryhex': '#fff71c',
  'secondaryhex': '#e3002d',
  'team': 'Watford FC'},
 {'id': 163,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'PAS Giannina'},
 {'id': 164,
  'primaryhex': '#F0F027',
  'secondaryhex': '#3910E0',
  'team': 'Chievo Verona'},
 {'id': 165,
  'primaryhex': '#009932',
  'secondaryhex': '#FFFFFF',
  'team': 'Hannover 96'},
 {'id': 166,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Panathinaikos Athens'},
 {'id': 167,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Toulouse'},
 {'id': 168,
  'primaryhex': '#000000',
  'secondaryhex': '#ffffff',
  'team': 'FC Lugano'},
 {'id': 169,
  'primaryhex': '#00954C',
  'secondaryhex': '#ffffff',
  'team': 'Real Betis Balompié'},
 {'id': 170,
  'primaryhex': '#D10019',
  'secondaryhex': '#000000',
  'team': 'FC Admira Wacker Mödling'},
 {'id': 171,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Antalyaspor'},
 {'id': 172,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FF0000',
  'team': 'Aberdeen FC'},
 {'id': 173,
  'primaryhex': '#dcecf2',
  'secondaryhex': '#ffffff',
  'team': 'SS Lazio'},
 {'id': 174,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Atromitos Athen'},
 {'id': 175,
  'primaryhex': '#216bff',
  'secondaryhex': '#ffffff',
  'team': 'Levski Sofia'},
 {'id': 176,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Hamilton Academical FC'},
 {'id': 177,
  'primaryhex': '#FDB913',
  'secondaryhex': '#231F20',
  'team': 'Wolverhampton Wanderers'},
 {'id': 178,
  'primaryhex': '#0064B9',
  'secondaryhex': '#FDFDFB',
  'team': 'Grasshopper Club Zurich'},
 {'id': 179,
  'primaryhex': '#0033CC',
  'secondaryhex': '#CC0000',
  'team': 'Miedz Legnica'},
 {'id': 180,
  'primaryhex': '#fff200',
  'secondaryhex': '#00b6d6',
  'team': 'FC Astana'},
 {'id': 181,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Östersunds FK'},
 {'id': 182,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Stade Reims'},
 {'id': 183,
  'primaryhex': '#E41349',
  'secondaryhex': '#FFFFFF',
  'team': 'Red Bull Salzburg'},
 {'id': 184,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFFF',
  'team': 'Cercle Brugge '},
 {'id': 185,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Kalmar FF'},
 {'id': 186,
  'primaryhex': '#0a0909',
  'secondaryhex': '#264deb',
  'team': 'Atalanta BC'},
 {'id': 187,
  'primaryhex': '#001bc7',
  'secondaryhex': '#ffffff',
  'team': 'Zhetysu Taldykorgan'},
 {'id': 188,
  'primaryhex': '#fff200',
  'secondaryhex': '#f20303',
  'team': 'Korona Kielce'},
 {'id': 189,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'GIF Sundsvall'},
 {'id': 190,
  'primaryhex': '#154281',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Luzern'},
 {'id': 191,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Athletic Bilbao'},
 {'id': 192,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'NK Lokomotiva Zagreb'},
 {'id': 193,
  'primaryhex': '#fa0808',
  'secondaryhex': '#ffffff',
  'team': 'Vejle Boldklub'},
 {'id': 194,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Arsenal Kyiv'},
 {'id': 195,
  'primaryhex': '#004CFF',
  'secondaryhex': '#FFFFFF',
  'team': 'Hertha BSC'},
 {'id': 196,
  'primaryhex': '#000000',
  'secondaryhex': '#f70000',
  'team': 'SBV Excelsior Rotterdam'},
 {'id': 197,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Kasimpasa'},
 {'id': 198,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'EA Guingamp'},
 {'id': 199,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'OFI Crete'},
 {'id': 200,
  'primaryhex': '#610909',
  'secondaryhex': '#ffffff',
  'team': 'AE Larisa'},
 {'id': 201,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'KAS Eupen'},
 {'id': 202,
  'primaryhex': '#ffffff',
  'secondaryhex': '#d91111',
  'team': 'FK Vozdovac'},
 {'id': 203,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Botosani'},
 {'id': 204,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Gaz Metan Medias'},
 {'id': 205,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFFF',
  'team': 'Vorskla Poltava'},
 {'id': 206,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'AC Horsens'},
 {'id': 207,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Eintracht Frankfurt'},
 {'id': 208,
  'primaryhex': '#0054A6',
  'secondaryhex': '#ffffff',
  'team': 'Brighton &amp; Hove Albion'},
 {'id': 209,
  'primaryhex': '#343ccf',
  'secondaryhex': '#ffffff',
  'team': 'FK Radnik Surdulica'},
 {'id': 210,
  'primaryhex': '#004793',
  'secondaryhex': '#FFFFFF',
  'team': 'Chelsea FC'},
 {'id': 211,
  'primaryhex': '#ff0808',
  'secondaryhex': '#FFFFFF',
  'team': 'Feyenoord Rotterdam'},
 {'id': 212,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'RCD Espanyol Barcelona'},
 {'id': 213,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'IF Elfsborg'},
 {'id': 214,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'LASK'},
 {'id': 215,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Slovan Liberec'},
 {'id': 216,
  'primaryhex': '#CC0000',
  'secondaryhex': '#FFFFFF',
  'team': 'CFR Cluj'},
 {'id': 217,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'KV Kortrijk'},
 {'id': 218,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'Rayo Vallecano'},
 {'id': 219,
  'primaryhex': '#e80c0c',
  'secondaryhex': '#ffffff',
  'team': 'SC Braga'},
 {'id': 220,
  'primaryhex': '#DFE60C',
  'secondaryhex': '#06167D',
  'team': 'Dunarea Calarasi'},
 {'id': 221,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Piast Gliwice'},
 {'id': 222,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Rangers FC'},
 {'id': 223,
  'primaryhex': '#E80C38',
  'secondaryhex': '#FFFFFF',
  'team': 'Bayern Munich'},
 {'id': 224,
  'primaryhex': '#009900',
  'secondaryhex': '#FF0000',
  'team': 'KV Oostende'},
 {'id': 225,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Waasland-Beveren'},
 {'id': 226,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'HSC Montpellier'},
 {'id': 227,
  'primaryhex': '#ff7700',
  'secondaryhex': '#000000',
  'team': 'Shakhter Karaganda'},
 {'id': 228,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Kilmarnock FC'},
 {'id': 229,
  'primaryhex': '#ffffff',
  'secondaryhex': '#e30707',
  'team': 'FK Aktobe'},
 {'id': 230,
  'primaryhex': '#fc0505',
  'secondaryhex': '#0303fa',
  'team': 'Panionios Athens'},
 {'id': 231,
  'primaryhex': '#B3040C',
  'secondaryhex': '#FFFFFF',
  'team': 'CSKA Sofia'},
 {'id': 232,
  'primaryhex': '#008000',
  'secondaryhex': '#FFFFFF',
  'team': 'Concordia Chiajna'},
 {'id': 233,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'MFK Karvina'},
 {'id': 234,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Fortuna Düsseldorf'},
 {'id': 235,
  'primaryhex': '#099902',
  'secondaryhex': '#000000',
  'team': 'US Sassuolo'},
 {'id': 236,
  'primaryhex': '#1D3DC8',
  'secondaryhex': '#F6D000',
  'team': 'SKN St. Pölten'},
 {'id': 237,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'SCO Angers'},
 {'id': 238,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#FF0000',
  'team': 'VfB Stuttgart'},
 {'id': 239,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Zorya Luhansk'},
 {'id': 240,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC FASTAV Zlin'},
 {'id': 241,
  'primaryhex': '#0000ff',
  'secondaryhex': '#ffffff',
  'team': 'Real Sociedad'},
 {'id': 242,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Jablonec'},
 {'id': 243,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Slezsky FC Opava'},
 {'id': 244,
  'primaryhex': '#CC0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Willem II Tilburg'},
 {'id': 245,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Aris Thessaloniki'},
 {'id': 246,
  'primaryhex': '#00a6e8',
  'secondaryhex': '#031669',
  'team': 'Djurgardens IF'},
 {'id': 247,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'NK Istra 1961'},
 {'id': 248,
  'primaryhex': '#FF6600',
  'secondaryhex': '#33CC00',
  'team': 'Alanyaspor'},
 {'id': 249,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Viktoria Plzen'},
 {'id': 250,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'IFK Norrköping'},
 {'id': 251,
  'primaryhex': '#d9020d',
  'secondaryhex': '#ffffff',
  'team': 'Manchester United'},
 {'id': 252,
  'primaryhex': '#F50C0C',
  'secondaryhex': '#FFFFFF',
  'team': 'Red Star Belgrade'},
 {'id': 253,
  'primaryhex': '#0033CC',
  'secondaryhex': '#FFFFFF',
  'team': 'TSG 1899 Hoffenheim'},
 {'id': 254,
  'primaryhex': '#FF0033',
  'secondaryhex': '#FFFFFF',
  'team': 'Southampton FC'},
 {'id': 255,
  'primaryhex': '#eb0000',
  'secondaryhex': '#ffffff',
  'team': 'Kaysar Kyzylorda'},
 {'id': 256,
  'primaryhex': '#339900',
  'secondaryhex': '#FFFFFF',
  'team': 'Karpaty Lviv'},
 {'id': 257,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#173880',
  'team': 'Real Madrid'},
 {'id': 258,
  'primaryhex': '#000000',
  'secondaryhex': '#ffffff',
  'team': 'FK Partizan Belgrade'},
 {'id': 259,
  'primaryhex': '#ffffff',
  'secondaryhex': '#0009b0',
  'team': 'Górnik Zabrze'},
 {'id': 260,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Borussia Mönchengladbach'},
 {'id': 261,
  'primaryhex': '#000979',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Girondins Bordeaux'},
 {'id': 262,
  'primaryhex': '#FDF105',
  'secondaryhex': '#000000',
  'team': 'Borussia Dortmund'},
 {'id': 263,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Vereya Stara Zagora'},
 {'id': 264,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Newcastle United'},
 {'id': 265,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FFFFFF',
  'team': 'Chornomorets Odessa'},
 {'id': 266,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFFF',
  'team': 'Slask Wroclaw'},
 {'id': 267,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'PAOK Thessaloniki'},
 {'id': 268,
  'primaryhex': '#681938',
  'secondaryhex': '#2DB2EB',
  'team': 'Trabzonspor'},
 {'id': 269,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Heracles Almelo'},
 {'id': 270,
  'primaryhex': '#ED1C23',
  'secondaryhex': '#FFFFFF',
  'team': 'PSV Eindhoven'},
 {'id': 271,
  'primaryhex': '#FCFCFC',
  'secondaryhex': '#0A0909',
  'team': 'Juventus FC'},
 {'id': 272,
  'primaryhex': '#0066FF',
  'secondaryhex': '#FFFFFF',
  'team': 'De Graafschap Doetinchem'},
 {'id': 273,
  'primaryhex': '#0470c2',
  'secondaryhex': '#ffffff',
  'team': 'SPAL'},
 {'id': 274,
  'primaryhex': '#1bc7de',
  'secondaryhex': '#ffffff',
  'team': 'FK Spartak Subotica'},
 {'id': 275,
  'primaryhex': '#0000CC',
  'secondaryhex': '#FFFFFF',
  'team': 'SC Heerenveen'},
 {'id': 276,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Nantes'},
 {'id': 277,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Sivasspor'},
 {'id': 278,
  'primaryhex': '#0026e6',
  'secondaryhex': '#ffffff',
  'team': 'FK Mladost Lucani'},
 {'id': 279,
  'primaryhex': '#ab0a0a',
  'secondaryhex': '#0f0f6b',
  'team': 'Cagliari Calcio'},
 {'id': 280,
  'primaryhex': '#fffb00',
  'secondaryhex': '#0000ff',
  'team': 'Parma Calcio 1913'},
 {'id': 281,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Desportivo Aves'},
 {'id': 282,
  'primaryhex': '#ff0000',
  'secondaryhex': '#ffffff',
  'team': 'Girona FC'},
 {'id': 283,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'SL Benfica'},
 {'id': 284,
  'primaryhex': '#e0223C',
  'secondaryhex': '#FFFFFF',
  'team': 'RB Leipzig'},
 {'id': 285,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Lviv'},
 {'id': 286,
  'primaryhex': '#0072CE',
  'secondaryhex': '#FFFFFF',
  'team': 'Huddersfield Town'},
 {'id': 287,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'CS Marítimo'},
 {'id': 288,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Sepsi Sf. Gheorghe'},
 {'id': 289,
  'primaryhex': '#0000FF',
  'secondaryhex': '#000000',
  'team': 'FC Viitorul '},
 {'id': 290,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Randers FC'},
 {'id': 291,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Apollon Smyrnis'},
 {'id': 292,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Stade Rennais FC'},
 {'id': 293,
  'primaryhex': '#ff0000',
  'secondaryhex': '#ffffff',
  'team': 'FK Ufa'},
 {'id': 294,
  'primaryhex': '#d9020d',
  'secondaryhex': '#FFFFFF',
  'team': 'CSKA Moscow'},
 {'id': 295,
  'primaryhex': '#000066',
  'secondaryhex': '#F7FF00',
  'team': 'MKE Ankaragücü'},
 {'id': 296,
  'primaryhex': '#FF0000',
  'secondaryhex': '#000000',
  'team': 'Bayer 04 Leverkusen'},
 {'id': 297,
  'primaryhex': '#ff0000',
  'secondaryhex': '#ffffff',
  'team': 'FC Emmen'},
 {'id': 298,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FC Midtjylland'},
 {'id': 299,
  'primaryhex': '#00003d',
  'secondaryhex': '#730000',
  'team': 'Pogon Szczecin'},
 {'id': 300,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'OGC Nice'},
 {'id': 301,
  'primaryhex': '#e0e316',
  'secondaryhex': '#0011ff',
  'team': 'FK Rostov'},
 {'id': 302,
  'primaryhex': '#FF0000',
  'secondaryhex': '#0000FF',
  'team': 'Royal Excel Mouscron '},
 {'id': 303,
  'primaryhex': '#0053A0',
  'secondaryhex': '#FDBE11',
  'team': 'Leicester City'},
 {'id': 304,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Cracovia Kraków'},
 {'id': 305,
  'primaryhex': '#660808',
  'secondaryhex': '#73e8f0',
  'team': 'Burnley FC'},
 {'id': 306,
  'primaryhex': '#FF1433',
  'secondaryhex': '#004093',
  'team': 'FC Basel 1893'},
 {'id': 307,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#000066',
  'team': 'Fenerbahce SK'},
 {'id': 308,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Utrecht'},
 {'id': 309,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'POFK Botev Vratsa'},
 {'id': 310,
  'primaryhex': '#029907',
  'secondaryhex': '#ffffff',
  'team': 'PFC Beroe Stara Zagora'},
 {'id': 311,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'IFK Göteborg'},
 {'id': 312,
  'primaryhex': '#000066',
  'secondaryhex': '#FFFFFF',
  'team': 'Dundee FC'},
 {'id': 313,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Wolfsberger AC'},
 {'id': 314,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Olimpik Donetsk'},
 {'id': 315,
  'primaryhex': '#FFCC00',
  'secondaryhex': '#660033',
  'team': 'Motherwell FC'},
 {'id': 316,
  'primaryhex': '#e1ff00',
  'secondaryhex': '#226b05',
  'team': 'CD Tondela'},
 {'id': 317,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'APO Levadiakos'},
 {'id': 318,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Spartak Moscow'},
 {'id': 319,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#0000FF',
  'team': 'Arka Gdynia'},
 {'id': 320,
  'primaryhex': '#ed7300',
  'secondaryhex': '#ffffff',
  'team': 'Zaglebie Lubin'},
 {'id': 321,
  'primaryhex': '#000000',
  'secondaryhex': '#ff0000',
  'team': 'Neuchâtel Xamax FCS'},
 {'id': 322,
  'primaryhex': '#004B92',
  'secondaryhex': '#FFFFFF',
  'team': 'Lech Poznan'},
 {'id': 323,
  'primaryhex': '#CC0000',
  'secondaryhex': '#ffffff',
  'team': 'Rubin Kazan'},
 {'id': 324,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#099FFF',
  'team': 'Olympique Marseille'},
 {'id': 325,
  'primaryhex': '#660033',
  'secondaryhex': '#0099FF',
  'team': 'West Ham United'},
 {'id': 326,
  'primaryhex': '#ec1F00',
  'secondaryhex': '#ffffff',
  'team': 'FC Sion'},
 {'id': 327,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#ffffff',
  'team': 'Vendsyssel FF'},
 {'id': 328,
  'primaryhex': '#006600',
  'secondaryhex': '#FFFFff',
  'team': 'Anzhi Makhachkala'},
 {'id': 329,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'Besiktas JK'},
 {'id': 330,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'CD Feirense'},
 {'id': 331,
  'primaryhex': '#003E80',
  'secondaryhex': '#D9031C',
  'team': 'GD Chaves'},
 {'id': 332,
  'primaryhex': '#ffd940',
  'secondaryhex': '#000002',
  'team': 'BSC Young Boys'},
 {'id': 333,
  'primaryhex': '#ffffff',
  'secondaryhex': '#000000',
  'team': 'FK Cukaricki'},
 {'id': 334,
  'primaryhex': '#ffdd00',
  'secondaryhex': '#004393',
  'team': 'Frosinone Calcio'},
 {'id': 335,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Sevilla FC'},
 {'id': 336,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'NK Rudes'},
 {'id': 337,
  'primaryhex': '#0000FF',
  'secondaryhex': '#FF0000',
  'team': 'FCSB'},
 {'id': 338,
  'primaryhex': '#005F27',
  'secondaryhex': '#FFFFFF',
  'team': 'PFK Ludogorets Razgrad'},
 {'id': 339,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Asteras Tripolis'},
 {'id': 340,
  'primaryhex': '#F00000',
  'secondaryhex': '#0021F5',
  'team': 'FK Radnicki Nis'},
 {'id': 341,
  'primaryhex': '#FFFFFF',
  'secondaryhex': '#001C58',
  'team': 'Tottenham Hotspur'},
 {'id': 342,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Nîmes Olympique'},
 {'id': 343,
  'primaryhex': '#ffb22e',
  'secondaryhex': '#9e142b',
  'team': 'AS Roma'},
 {'id': 344,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Örebro SK'},
 {'id': 345,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Büyüksehir Belediye Erzurumspor'},
 {'id': 346,
  'primaryhex': '#00bfff',
  'secondaryhex': '#FDFDFB',
  'team': 'FC Zürich'},
 {'id': 347,
  'primaryhex': '#FFAE00',
  'secondaryhex': '#FF0000',
  'team': 'Galatasaray SK'},
 {'id': 348,
  'primaryhex': '#000000',
  'secondaryhex': '#ffea00',
  'team': 'Kairat Almaty'},
 {'id': 349,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': '1.FK Pribram'},
 {'id': 350,
  'primaryhex': '#0000CC',
  'secondaryhex': '#CC0000',
  'team': 'FC Barcelona'},
 {'id': 351,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Athletic Eskilstuna'},
 {'id': 352,
  'primaryhex': '#025FAC',
  'secondaryhex': '#FFFFFF',
  'team': 'FC Schalke 04'},
 {'id': 353,
  'primaryhex': '#FFD500',
  'secondaryhex': '#DB0000',
  'team': 'Jagiellonia Bialystok'},
 {'id': 354,
  'primaryhex': '#000000',
  'secondaryhex': '#00703C',
  'team': 'FC Wacker Innsbruck'},
 {'id': 355,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'CD Santa Clara'},
 {'id': 356,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'Rio Ave FC'},
 {'id': 357,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'AS Monaco'},
 {'id': 358,
  'primaryhex': '#BF0C10',
  'secondaryhex': '#0C0D0F',
  'team': 'AFC Bournemouth'},
 {'id': 359,
  'primaryhex': '#FFFF00',
  'secondaryhex': '#FF0000',
  'team': 'Göztepe'},
 {'id': 360,
  'primaryhex': '#07078a',
  'secondaryhex': '#e60707',
  'team': 'Genoa CFC'},
 {'id': 361,
  'primaryhex': '#000000',
  'secondaryhex': '#FFFFFF',
  'team': 'St. Mirren FC'},
 {'id': 362,
  'primaryhex': '#ffffff',
  'secondaryhex': '#1a7812',
  'team': 'Hammarby IF'},
 {'id': 363,
  'primaryhex': '#0000CC',
  'secondaryhex': '#CC0000',
  'team': 'Levante UD'},
 {'id': 364,
  'primaryhex': '#006633',
  'secondaryhex': '#FFFFFF',
  'team': 'Hibernian FC'},
 {'id': 365,
  'primaryhex': '#ffffff',
  'secondaryhex': '#009c3c',
  'team': 'Lechia Gdansk'},
 {'id': 366,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'FK Teplice'},
 {'id': 367,
  'primaryhex': '#FF0000',
  'secondaryhex': '#FFFFFF',
  'team': 'Arsenal FC'},
 {'id': 368,
  'primaryhex': '#317a2b',
  'secondaryhex': '#ffffff',
  'team': 'FC Bohemians Prag 1905'},
 {'id': 369,
  'primaryhex': '#008543',
  'secondaryhex': '#FFFFFF',
  'team': 'Rapid Vienna'},
 {'id': 370,
  'primaryhex': '#009933',
  'secondaryhex': '#FFFFFF',
  'team': 'Celtic FC'},
 {'id': 371,
  'primaryhex': '#056600',
  'secondaryhex': '#ffffff',
  'team': 'FK Atyrau'},
 {'id': 372,
  'primaryhex': '#ffffff',
  'secondaryhex': '#ffffff',
  'team': 'NK Inter Zapresic'},
 {'id': 373,
  'primaryhex': '#0d6ecd',
  'secondaryhex': '#FFFFFF',
  'team': 'Dinamo Moscow'},
 {'id': 374,
  'primaryhex': '#0000CC',
  'secondaryhex': '#FFFFFF',
  'team': 'Wisla Plock'}]
 export default TeamData